nipreps/niworkflows

Dockerfile
niworkflows/info.py
niworkflows/interfaces/registration.py

This PR fixes nipype dependency. Previously defined dependency_links was ignored and the latest release of nipype was always used (which is probably why @shoshber attempts to use her own fork of nipype in #36 did not work).
I assumed that using nipype master is intended and it might be temporarily necessary. For pypy releases we should not use dependency_links and only depend on relesed packages.

[RTM] nipype source

---

niworkflows/common/report.py
niworkflows/interfaces/registration.py
niworkflows/tests/test_reports.py
niworkflows/viz/utils.py

In the artifacts on circle, it shows the outline of the brain mask. This is because it is more convenient in testing to use already-available files.
Here is what it looks like with a white matter outline: https://github.com/shoshber/pastebin/blob/master/reports/wm_mask.svg

WIP/ENH plot outline of FLIRT input wm_seg

---

niworkflows/anat/mni.py

Fixes previously reported problems with subject 100103 in ds054 (see https://github.com/poldracklab/fmriprep/issues/266). I also tested it on one subject from ds005 and one subject from the beast to make sure it does not reintroduce problems. This approach even though not fully intuitive has been suggested on the ANTs forum in the past: https://sourceforge.net/p/advants/discussion/840261/thread/27216e69/#c7ba

[RTM] Use masked images by default in robust normalization

---

niworkflows/common/report.py
niworkflows/interfaces/segmentation.py
niworkflows/tests/test_reports.py
niworkflows/viz/utils.py

As discussed in #102, shows white/pial surfaces overlaid on masked T1.
`SurfaceSegmentationRC` is derived more from `RegistrationRC` with the "moving" image removed, as FreeSurfer doesn't have quite the equivalents of FAST's 3-class output files... `aseg.mgz` could be used, but it has many subcortical divisions, which would need to be mapped into white, gray, and possibly CSF.
As recon-all is very long to run, report interfaces are extended to allow mock runs, which assumes necessary files have already been created. At present, I believe this requires that the necessary files can be derived from the InputSpec, as the OutputSpec shouldn't be properly instantiated.
Closes #102.

ReconAll report

---

Dockerfile
niworkflows/common/report.py
niworkflows/tests/test_reports.py
niworkflows/viz/utils.py

This adds two-fold compression to SVG reportlets:
- paths in SVG are optimized using `svgo`
- bitmaps are converted to webp and compressed at 80%
The compression is only performed if the necessary tools are present.

[RTM] Added optional svg compression

---

niworkflows/info.py
niworkflows/interfaces/segmentation.py
requirements.txt

nipy/nipype#1784 has been merged, so we can track nipype/master. Remove version constraint from `info.py`, to avoid overwriting pinned copy.
Precondition for poldracklab/fmriprep#347.

[RTM] Typo fixed in nipype

---

niworkflows/interfaces/registration.py

The reporting in `BBRegisterRPT` ignores `subjects_dir` when passed through nipype.
Also prefers `brainmask.mgz` to `T1.mgz`, to more closely resemble the output of `FLIRTRPT`.

BBRegisterRPT: Use inputs.subjects_dir to find structurals

---

niworkflows/viz/utils.py

Specifically checks for `ENOENT`, raising other `OSError`s.
Also sets `stdin=/dev/null` to avoid hanging on programs that expect input (e.g. bash, which I used to test).
Closes #129.

Python 2-compatible FileNotFoundError

---

niworkflows/common/report.py

Should be an easy one. I'll check the artifacts and merge if the ReconAll output is compressed.
Fixes #132.

Compress surface segmentation reports

---

.circle/pytests.sh
.dockerignore
CHANGES.rst
Dockerfile
circle.yml
niworkflows/info.py
niworkflows/tests/test_reports.py
niworkflows/tests/viz/test_utils.py
niworkflows/viz/utils.py

This PR has grown up:
- [FIXED] Started with the problem of subprocess.run is not python 2 compatible
- [Fix #45] Added Python 2.7 tests in circle.
- [Fix #55] Migrated tests to py.test, and tests run with `-v` flag which outputs all the logging output from nipype.
- [Fix #52] Used plain assertions that work in both python 2 and 3.
- Additionally, enabled 2x parallelism in CircleCI (please enable on your settings @chrisfilo, @effigies, @rwblair )
WARNING: I have disabled the test in tests/viz/test_utils. The test always fails, I suspect nosetests wasn't actually running this. If this test is exercising some of the code other tests are not, please help me fix the test. Remove otherwise.

[RTM] Python 2 tests and fixes

---

niworkflows/interfaces/registration.py
requirements.txt

If we want to use `bbregister --init-coreg`, we need to derive the inputspec from `BBRegisterInputSpec6`.
If we want to support FS5.3 in niworkflows, I can run a version check for defining `BBRegisterInputSpecRPT`.

[RTM] Derive BBRegisterInputSpecRPT from BBRegisterInputSpec6

---

.circle/pytests.sh
CHANGES.rst
niworkflows/interfaces/__init__.py
niworkflows/interfaces/registration.py
niworkflows/tests/test_reports.py

This interface generates a registration report with the
before and after labels using its `before` and `after` inputs.
It does not run any internal interface.
Use case:
Generate a report of the EPI before and after unwarping with the WM mask, so it is not necessary to clutter the EPI preprocessing workflow with the white matter input. It can be generated outside.

[ENH] Add a SimpleBeforeAfter report capable interface

---

niworkflows/interfaces/registration.py

The version check neglected the possibility of constructing workflows for documentation purposes. This fixes the doc issues.
https://fmriprep.readthedocs.io/en/fix_docs/workflows.html

FIX: Use FS6 BBR spec in absence of FS

---

niworkflows/interfaces/registration.py
requirements.txt

This PR moves to a dependency on an updated version check. This would have broken things for people updating nipype since ~8am EDT today. This would not affect any Docker builds, due to the earlier requirement. FMRIPREP should be moved to this same nipype commit ASAP once this is merged.
Closes #151.

Move to fs.Info.looseversion() to check FreeSurfer version

---

niworkflows/interfaces/base.py
niworkflows/interfaces/registration.py

This exists as both [`mriqc.interfaces.base.MRIQCBaseInterface`](https://github.com/poldracklab/mriqc/blob/master/mriqc/interfaces/base.py#L11) and [`fmriprep.interfaces.bids.SimpleInterface`](https://github.com/poldracklab/fmriprep/blob/master/fmriprep/interfaces/bids.py#L38).

[RTM] Add SimpleInterface subclass of BaseInterface

---

niworkflows/data/__init__.py
niworkflows/data/getters.py

This is intended to enable poldracklab/fmriprep#498. It enables selecting a data grabber by template name as used in fmriprep.

ENH: Expose get_dataset and a template name-resource map

---

niworkflows/anat/mni.py
niworkflows/info.py
niworkflows/tests/test_reports.py
requirements.txt

This version will resolve to `< 0.0.7`, which allows us to use meaningful deprecation versions, as discussed in #157.
This approach maintains the ability for Circle to replace the version on release, as well as allows meaningful version comparisons for git repositories. The additional work of updating the dev version number occurs *after* the release, so there's no risk of this resulting in a need for a quick release cycle because we screwed up the version number.
@oesteban mentioned a new system he's using in MRIQC. I'm okay with switching to that if that seems like a better option.
Fixes #163

Dev version: Use last release + 0.0.1 + '-dev'

---

.gitmodules
Dockerfile
circle.yml
niworkflows/anat/mni.py
niworkflows/anat/skullstrip.py
niworkflows/common/orient.py
niworkflows/common/report.py
niworkflows/info.py
niworkflows/interfaces/base.py
niworkflows/interfaces/masks.py
niworkflows/interfaces/registration.py
niworkflows/interfaces/segmentation.py
niworkflows/interfaces/utils.py
niworkflows/nipype
niworkflows/tests/test_reports.py
niworkflows/viz/utils.py
requirements.txt
setup.py
tox.ini

First pass at resolving poldracklab/fmriprep#541.
This approach makes a submodule in the root directory and symlinks `niworkflows/nipype` to `../nipype/nipype`. From a little bit of research, the alternative seemed to involve keeping an actual copy of `nipype/nipype` in the source tree, using either `git subtree` or `git filter-branch`. I'm not entirely clear on the details of these approaches, so it's possible that this isn't actually the simplest method.

ENH: Import nipype as submodule

---

MANIFEST.in

Unfortunately, these are a serious pain to test without releases, so my last hot fix included fixes for [MRIQC](https://circleci.com/gh/effigies/mriqc/5), but not [FMRIPREP](https://circleci.com/gh/poldracklab/fmriprep/831) data dependencies.
@oesteban @chrisfilo Do you want to have a look to see if you see any other issues? I don't want to push 0.1.2 and find there's something that still needs doing.

HOTFIX: Update manifest

---

niworkflows/interfaces/masks.py
niworkflows/interfaces/registration.py
niworkflows/interfaces/segmentation.py

`FLIRT(save_log=True)` needs access to `runtime.stdout`. It seems like a good idea to pass `runtime` in all cases.

FIX: Pass runtime to aggregate_outputs

---

niworkflows/anat/mni.py
niworkflows/data/epi-mni_registration_precise_000.json
niworkflows/data/epi-mni_registration_precise_001.json
niworkflows/data/epi-mni_registration_precise_002.json
niworkflows/data/epi-mni_registration_testing_000.json
niworkflows/data/epi-mni_registration_testing_001.json
niworkflows/data/epi-mni_registration_testing_002.json
niworkflows/data/t1-mni_registration_fast_000.json
niworkflows/data/t1-mni_registration_precise_000.json
niworkflows/data/t1-mni_registration_precise_001.json
niworkflows/data/t1-mni_registration_precise_002.json
niworkflows/data/t1-mni_registration_testing_000.json
niworkflows/data/t1-mni_registration_testing_001.json
niworkflows/data/t1-mni_registration_testing_002.json

This PR allows using ANTs' default (double precision) and also adds a `float` input in `RobustMNINormalization` to allow for changing it.

[ENH] Do not enforce float precision for ANTs

---

niworkflows/interfaces/registration.py

Required to fix poldracklab/fmriprep#616.

[RTM] ENH: Clear header extensions when making ref image

---

niworkflows/interfaces/registration.py

We've dropped single-band reference images from our fmriprep, but if there are cases where the sbref contrast is better than anything we can estimate, this may be useful.

[RTM] ENH: Enable sbref to be passed to EstimateReferenceImage

---

niworkflows/interfaces/registration.py
niworkflows/interfaces/utils.py

Should address poldracklab/fmriprep#722
Adds a `fov_mask` input to `GenerateSamplingReference`. This mask corresponds to the brain mask calculated from the T1w, and should not contain the brain stem.
The mask is resampled into target space, and then the bounding box is calculated. Finally, the FoV is adjusted to that bounding box.

[ENH] Optional crop-to-FoV added into GenerateSamplingReference

---

niworkflows/viz/utils.py

The line delineating skull mask is too thick to see 1-2 voxel wide errors. This PR reduces thickness to the same level as used in ReconAll reportlets and removes transparency (at 0.8 level I don't think it made a lot of difference).

Thinner lines in tissue segmentation

---

.circleci/config.yml

I'm pretty sure that `$CIRCLE_NPROCS` isn't set, and there are only actually 2 processors available.

CI: Let pytest-xdist auto-detect processors

---

niworkflows/interfaces/masks.py
niworkflows/interfaces/registration.py
niworkflows/interfaces/report_base.py
niworkflows/interfaces/segmentation.py

* `ReportCapableInputSpec` -> `SVGReportCapableInputSpec`
* Directly use Nipype's `ReportCapableOutputSpec`, `ReportCapableInterface`
* Input trait `inputs.generate_report` is now instance attribute `generate_report`
* `_post_run_hook` now generally ends with `return super._post_run_hook`
Depends on nipy/nipype#2560

RF: Use ReportCapableInterface from nipype

---

niworkflows/interfaces/utils.py

FIX: Avoid mmap when overwriting input (copyxform)

---

niworkflows/data/__init__.py
niworkflows/data/getters.py
niworkflows/data/utils.py
niworkflows/tests/test_data.py

- Added a new convenience method `get_template` that handles the `tpl-` prefix in a more reliable way.
- Organized list of datasets alphabetically
- Added a standardized revision of NKI (see OSF)
- Use of `pathlib.Path`
- Added a minimal set of tests for `niworkflows.data.utils._get_data_path`
- Fixed bug when downloading bids examples

[ENH/MAINT] Refactor downloads, update NKI

---

niworkflows/interfaces/registration.py

sbref support produced a situation in fMRIPrep where non-steady-state volumes were not even being identified in `EstimateReferenceImage`, even though they were passed to STC. They were being separately counted in confounds, but in poldracklab/fmriprep#1335, we switched to reusing the `EstimateReferenceImage` count, but also made it required to perform ICA-AROMA.
This led to poldracklab/fmriprep#1365.
This PR calculates non-steady-state volumes prior to checking for sbref files.
It also removes the somewhat pointless `data_slice` object.

FIX: Count non-steady-state volumes even if sbref is passed

---

niworkflows/viz/plots.py

Allow the summary plot to go on if one confound is fully nans

[FIX] Summary fMRIPlot chokes when confounds are all-nan

---

niworkflows/engine/workflows.py

When migrated from fmriprep, I replaced networkx.topological_sort
with nipype.pipeline.engine.utiles.topological_sort, which does not
have exactly the same interface (basically it wraps the iterable
within a list).

[HOTFIX] ``LiterateWorkflow`` returning empty desc

---

niworkflows/data/tests/crashfile.txt
niworkflows/utils/misc.py
niworkflows/viz/plots.py

Some minor fixes to get ``_read_txt`` to work again.

[FIX] ``read_crashfile`` stopped working after migration

---

niworkflows/data/utils.py

This PR is an attempt to fix ReadTheDocs builds (see poldracklab/fmriprep#1436).
The line
```Python
NIWORKFLOWS_CACHE_DIR = (Path.home() / '.cache' / 'stanford-crn').resolve()
```
is the primary problem, because, while this path may exist in the docker containers, it does not exist in the RTD environment. It's not clear that it needs to be resolved; this is just `realpath` as opposed to `abspath`, which is not needed to interact with a filesystem logically. Also removed the `.resolve()` from a list of files which are not checked for existence first.
```Python
return [Path(d).expanduser().resolve()
for d in data_dir.split(os.pathsep) if d.strip()] or default_dirs
```
Additionally removed the conversions from `Path`s to `str`s in some downstream variables, using `Path` methods instead of …

FIX: Do not resolve non-existent Paths

---

niworkflows/interfaces/mni.py

The current Enum is precluding the implementation of poldracklab/smriprep#11

[FIX] Allow arbitrary template names in ``RobustMNINormalization``

---

niworkflows/utils/bids.py

Addresses the issue posted in https://neurostars.org/t/fmriprep-from-singularity-unboundlocalerror/3299?u=oesteban

[HOTFIX] Fix ``UnboundLocalError`` in utils.bids

---

.circleci/config.yml

I think this is the cause of the codecov failures. Should see evidence in the submission steps.

CI: Checkout source for coverage reporting

---

niworkflows/interfaces/bids.py

We are writing CIfTI2 timeseries with extension .dtseries.nii. They break the DerivativesDataSink.

[HOTFIX] Only check headers of NIfTI files

---

.circleci/config.yml
niworkflows/viz/utils.py

Before (fieldmap of ds054 on fmriprep's reports at Circle):
After:

[FIX] Improve bounding box computation from masks

---

niworkflows/tests/test_viz.py
niworkflows/viz/utils.py

per @oesteban's [comment](https://github.com/poldracklab/fmriprep/pull/1467#issuecomment-457018934), this pull request attempts to add a warning to the figure if all components are listed as either signal or noise.
references poldracklab/fmriprep#1467
However, I must be needing to improve my matplotlib since even with this addition the warning does not appear to be displayed in the fmriprep reports.

[ENH] AROMA plots - add warning for edge cases (none/all are noise)

---

niworkflows/viz/plots.py

Realized I forgot to submit this. 
Fixing the scaling issue in #242. 
Scales the confounds based on the range of the values rather than scaling the min and max. 
if min value was 2 and max value was 5:
Before. ylim: 1.8 - 5.5 (plot displayed in 81% of ylim range)
Now, ylim: 1.7 - 5.3 (plot displayed in 83% of ylim range)
if min value was 900 and max value was 1000:
Before, ylim: 810 - 1100 (plot displayed in 34% of ylim range <- when squashing was occurring)
Now, ylim: 890 - 1010 (plot displayed in 83% of ylim range)

[FIX] Scaling of confound fix

---

niworkflows/interfaces/utils.py

I believe this is causing the issue in [Neurostars #3274](https://neurostars.org/t/fmriprep-resamples-bold-images-to-another-voxel-dimension-orientation/3274). Essentially we've been getting away with this because the majority of BOLD images come to us in LPS, which are just +/- flips in the affine matrix, not rotations causing the matrix to be off-diagonal.

FIX: GenerateSamplingReference with correct zooms

---

niworkflows/interfaces/bids.py

This PR makes the input spec of `DerivativesDataSink` dynamic. Those inputs set dynamically are considered metadata entries and stored to a sidecar JSON, if a single output file was sunk. If the output is more than one file metadata is dismissed (we may consider how to tackle multi-outputs in the future).
Close #308, enables poldracklab/fmriprep#1190, poldracklab/fmriprep#1384, poldracklab/smriprep#6

ENH: ``DerivativesDataSink`` - enable JSON sidecar writing

---

Dockerfile
niworkflows/__about__.py
niworkflows/interfaces/ants.py
niworkflows/interfaces/surf.py
requirements.txt

This PR adds the following new interfaces:

ENH: Add several helper interfaces

---

CHANGES.rst
niworkflows/tests/test_viz.py
niworkflows/viz/utils.py

Builds on #292 to improve the way these plots are written. Also adds a `[noise]` tag in the title of those components classified as such.

FIX: "NONE of the components..." banner was printed even when no AROMA file was present

---

niworkflows/anat/freesurfer.py

In order to prevent TemplateFlow's registration framework to have sMRIPrep as a dependency.

ENH: Upstream ``init_gifti_surface_wf`` from sMRIPrep

---

niworkflows/interfaces/registration.py

``EstimateReferenceImage`` generates 4D references if 4D SBRefs are supplied as input. This patch checks the dimensionality of SBRefs and generates an average if the SBRef is 4D.
Fixes poldracklab/fmriprep#1579.
Intimately related to #253, although I'm not sure the proposed resampling there is absolutely necessary.
It could be detrimental for ``bbregister`` in co-registration.
It is very likely necessary for head-motion correction with either ``mcflirt`` or ``3dVolReg``.

FIX: Do not generate 4D references out of 4D single-band references (SBRefs)

---

niworkflows/conftest.py
niworkflows/interfaces/bids.py
niworkflows/interfaces/tests/test_bids.py

Added two regression tests.
See #333 .

FIX: allow pipelining dynamic outputs of ``ReadSidecarJSON``

---

niworkflows/interfaces/utils.py

This pull request implements the following:
* `TSV2JSON` can now return a dictionary instead of printing contents to a JSON file. This is used to convert the TSV generated by the nipype `CompCor` interfaces into a dictionary, which can be passed to metadata sinks to produce JSON-formatted metadata. Perhaps this entails renaming the function?
* A new interface, `MergeDict`, merges dictionaries. This is used to combine metadata produced by different confound modelling steps in `fmriprep`. It wouldn't surprise me to learn that there's already an interface somewhere that does this; if so, please let me know so that I can update the code to use that instead. (The node is configured to support ordered output, but I haven't added the code to do that yet because I wasn't sure if there was already …

ENH: Dictionary manipulation / TSV to dict, merge multiple dicts

---

niworkflows/anat/ants.py

An additional INU correction step is included to run on the original
images (without truncating). Two further improvements are also being added:
1. if ATROPOS was run (``atropos_refine == True``), the WM tissue probability map is used
2. the N4 algorithm is configured with 5 iterations instead of 4 for a
more homogeneous white matter (close poldracklab/smriprep#38).
This PR may help alleviate the problem in poldracklab/smriprep#19, and
https://neurostars.org/t/fmriprep-t1-surface-issues/4089

ENH: run a second ``N4BiasFieldCorrection`` node to refine INU correction

---

niworkflows/reports/fmriprep.yml

This PR updates the fMRIPrep report specification to include derivatives
generated in the context of poldracklab/fmriprep#1586

ENH: Add new confounds model to reports template

---

niworkflows/interfaces/bids.py
niworkflows/interfaces/tests/test_bids.py

This may not be necessary if we fix compression, but this test I'm starting with should error and be fixed in either case.
Related: https://github.com/poldracklab/fmriprep/issues/1555

FIX: BusError in ``DerivativesDataSink``

---

niworkflows/interfaces/utils.py

This PR makes ``GenerateSamplingReference`` more flexible, accepting a
new input called ``resolution`` so that the decision about whether
generating a new resampling grid or not can be done in the context of
this interface.

FIX: Allow ``native`` grids (i.e. pass-through) for ``GenerateSamplingReference``

---

niworkflows/interfaces/bids.py
niworkflows/interfaces/tests/test_bids.py

Reverts poldracklab/niworkflows#350 pending a fix in nibabel for `mmap` options in loading `Cifti2Image`s.

Revert "FIX: BusError in ``DerivativesDataSink``"

---

niworkflows/interfaces/utility.py

This interface is akin to Python's ``OrderedDict``. It allows
to demultiplex list of dynamic lists (of same length) at the input
selecting the values corresponding to the requested key.
The implementation is proposed with several doctests ensuring the proper
functionality.
Pinging @satra and @effigies to know whether we should upstream this
interface directly to nipype.interfaces.utility

ENH: Add a ``KeySelect`` interface

---

niworkflows/reports/core.py
niworkflows/reports/fmriprep.yml
niworkflows/viz/utils.py

Builds upon #344, #346, #349, #351, and #352

ENH: Miscellaneous improvements to the Reports

---

niworkflows/anat/ants.py

We should be able to construct workflows in the absence of an ANTs installation, e.g., when building documentation.

FIX: Tolerate missing ANTs at workflow construction

---

niworkflows/anat/ants.py
niworkflows/interfaces/utils.py

This addresses point 2 of poldracklab/smriprep#82 and will collaborate in solving poldracklab/fmriprep#161.
Changes:

ENH: Ensure consistency of headers along brain extraction workflow

---

.circleci/config.yml
.travis.yml
Dockerfile
long_description.rst
niworkflows/__about__.py
niworkflows/__init__.py
niworkflows/tests/conftest.py
niworkflows/utils/tests/test_utils.py
pyproject.toml
setup.cfg
setup.py
versioneer.py

Validating installation methods and version stamping with Travis. Going to end up with a pretty big matrix (3 versions by 7 environments, at least), but for a project that a lot of our stuff depends on, I think it's worth it.
Closes #373.

MAINT: Switch to a ``setup.cfg``-based setup

---

.circleci/config.yml
.travis.yml
Dockerfile
niworkflows/__about__.py
niworkflows/interfaces/bids.py
niworkflows/reports/core.py
niworkflows/reports/figures.json
niworkflows/reports/fmriprep.yml
niworkflows/tests/test_segmentation.py
niworkflows/utils/bids.py
requirements.txt
setup.cfg

This is a pre-condition for:
* poldracklab/mriqc#776
* poldracklab/smriprep#93
* poldracklab/fmriprep#1694
Depends on:
* templateflow/python-client#15

MAINT: Use PyBIDS 0.9.2+

---

.circleci/config.yml
setup.cfg

It looks like nilearn doesn't correctly specify requirements, so scikit-learn is not installed when nilearn is. However, importing nilearn fails if scikit-learn is missing, so we'll do it ourselves.

FIX: Require scikit-learn because nilearn does not

---

MANIFEST.in
niworkflows/data/itkIdentityTransform.txt
niworkflows/interfaces/itk.py
niworkflows/interfaces/tests/test_itk.py
setup.cfg

This causes a BusError reported in [NeuroStars #4641](https://neurostars.org/t/bus-error-fmriprep/4641).

FIX: Load file with mmap=False when modifying on-disk dtype

---

.circleci/config.yml
niworkflows/data/epi_atlasbased_brainmask.json
niworkflows/func/tests/test_util.py
niworkflows/func/util.py

This PR adds a new build job to the CircleCI workflow to tests regressions on the EPI masking workflows migrated from fMRIPrep (#362).
The infrastructure and tests are replicated from fMRIPrep.
The PR makes CircleCI ignore these tests (branches and tags) except for `master` and branches with name `masks?/*` to minimize churn.
Incidentally, minor fixes to #362 are included.
Closes #371

TST: Bring EPI brain extraction tests from fMRIPrep

---

niworkflows/interfaces/segmentation.py

This PR tries to resolve a bug introduced in #337. When MELODIC did not
converge, `self._out_report` was rewritten from the input although it
had been manipulated before.
For reliability, the MELODICRPT interface is not a mixin anymore.

FIX: Revision of previous PR #337 / MELODIC did not converge

---

niworkflows/interfaces/bids.py
niworkflows/utils/images.py
niworkflows/utils/tests/test_images.py
setup.cfg

This provides an alternative to `img.to_filename` that hacks around nibabel's helpfulness to write the raw header and data block without applying or recalculating scale factors. In cases where the scale factors are non-identity, this avoids two full copies of the untouched data object at 64-bit float precision.
This comes with restrictions as to what you can do to the header between read and write, but the memory savings ought to be well worth it.
Inspired by https://github.com/poldracklab/fmriprep/issues/1740 and insomnia.

ENH: Memory optimized header rewriting

---

niworkflows/interfaces/utils.py

This minor fix should circumvent the crash in [the fmriprep confound metadata pull request](https://github.com/poldracklab/fmriprep/pull/1708).

[FIX] Ensure that length of indices matches length of values

---

niworkflows/anat/skullstrip.py
niworkflows/interfaces/nibabel.py
niworkflows/interfaces/tests/test_nibabel.py

This PR includes a very simplistic binarization interface using nibabel
to replace FSL's ``Threshold`` and others in the context of
poldracklab/mriqc#803.
The PR also updates AFNI's skull-stripping workflow to use it (removing
the dependency on FSL).

ENH: Add a new ``Binarize`` interface using nibabel

---

niworkflows/func/util.py

This was caught by @tsalo in #399. Pushing this change as it is unrelated to that PR.

FIX: Remove unused, undocumented output from the bold_reference workflow

---

niworkflows/reports/core.py
niworkflows/reports/fmriprep.yml

Addresses the problem spotted by @josephmje in https://github.com/nipreps/dmriprep/pull/28#issuecomment-547540822

ENH: Reports use the default template from niworkflows, allowing overwrite

---

.travis.yml

Scikit-image is an obnoxious dependency that breaks using `python setup.py {install,develop}` which is causing Travis failures.
Nobody installs this way anymore, so it's not worth supporting this use case. I'm just switching to `pip`.
Objections?

CI: Drop setup.py install/develop installs

---

niworkflows/anat/ants.py
niworkflows/func/tests/test_util.py
niworkflows/interfaces/cifti.py
niworkflows/interfaces/freesurfer.py
niworkflows/interfaces/images.py
niworkflows/interfaces/itk.py
niworkflows/interfaces/masks.py
niworkflows/interfaces/mni.py
niworkflows/interfaces/nilearn.py
niworkflows/interfaces/registration.py
niworkflows/interfaces/utils.py
niworkflows/tests/test_segmentation.py
niworkflows/tests/test_viz.py
niworkflows/viz/plots.py
niworkflows/viz/utils.py

For compatibility with nibabel:
```
find ./niworkflows -name "*.py" -exec sed -i 's+\.get_data(+.get_fdata(+g' {} \;
```

FIX: Update all SpatialImage.get_data -> get_fdata

---

.circleci/config.yml
.travis.yml
Dockerfile
niworkflows/conftest.py
niworkflows/interfaces/ants.py

This PR adds an input ``copy_header`` to the ``ImageMath`` and ``ThresholdImage`` interfaces because ANTs fails to produce images with appropriate x-form headers.
In particular, these changes are necessary for poldracklab/mriqc#803 to go forward.
In addition to the ``copy_header`` change, some PEP stylistic issues have been addressed.

ENH: Add ``copy_header`` inputs to some ANTs interfaces

---

niworkflows/interfaces/freesurfer.py
niworkflows/interfaces/tests/test_freesurfer.py

Fix for https://github.com/poldracklab/fmriprep/issues/1890.
FreeSurfer anatomical images are scaled to `uint8`s, so coercing to float was problematic.

FIX: Ensure data type of masked image matches T1.mgz

---

setup.cfg

https://docs.pytest.org/en/latest/deprecations.html#junit-family-default-value-change-to-xunit2

MNT: Specify junit_family to suppress pytest DeprecationWarning

---

niworkflows/interfaces/cifti.py
niworkflows/interfaces/freesurfer.py
setup.cfg

Enhance `GenerateCifti`, `MedialNaNs`, and `CiftiNameSource` interfaces to support HCP grayordinates.
This change depends on templateflow/python-client#31

ENH: expand GenerateCifti & MedialNaNs interfaces to support HCP grayordinates / fsLR surfaces

---

niworkflows/func/tests/test_util.py
niworkflows/func/util.py

fixes #437 
adds tests to confirm functionality.

[FIX] handle case when dummy_scans is 0

---

niworkflows/interfaces/cifti.py
niworkflows/interfaces/surf.py

- Adds new `density` output to `GenerateCifti` interface to allow tracking CIFTI file density (grayordinates)
- Adds `density` to `NameCifti` to differentiate low/high res data.
- Adds `template_kwargs` to `GiftiNameSource` to allow more flexible formatting

ENH: CIFTI / fsLR density

---

niworkflows/anat/ants.py

Allows skipping brain extraction with n4_only workflow.
See: https://github.com/poldracklab/smriprep/pull/116
I think the main remaining todo is this comment from @oesteban:
> I've been looking at some masks after binarization. I think they would benefit a lot from a binary opening followed by closing to remove the irregular boundary. Also, it would also make sense to fill holes. We might want to implement that as part of the Binarize interface. I'll have a look into this tomorrow.

ENH: Add ``n4_only`` workflow -- to skip brain extraction

---

niworkflows/interfaces/images.py
niworkflows/interfaces/tests/test_images.py

See poldracklab/sdcflows#77.
I'll try to add a regression test for this ASAP. For now, it'd be good to have your opinion on how I'm using nibabel, Chris.

FIX: ``IntraModalMerge`` failed for dims (x, y, z, 1)

---

niworkflows/conftest.py
niworkflows/utils/spaces.py
niworkflows/utils/tests/test_spaces.py
setup.cfg

(brought in from mgxd/niworkflows#1)
Okay, after much thinking, I believe this captures the whole set of requirements.
Now there is an ``Space`` object that makes all the validations and sanity checks. There is still room for enhancements:
- ~~We might want to implement a classmethod (something like ``Space.from_string``) that implements the parsing of ``--output-spaces`` arguments (see https://www.attrs.org/en/stable/init.html).~~ DONE
- We might want to check that the specs contain valid keywords against templateflow (at the moment, this is only done for cohort).
Other than that, I think the doctest examples show pretty much all the functionality.
Then, the ``SpatialReferences`` class is the one in charge of sorting out the available spaces. It has three convenience methods to filter …

ENH: Separate ``Space`` and ``SpatialReferences``

---

niworkflows/utils/spaces.py

- adds `cached` property to allow checkpointing `spaces`.
- this can be leveraged to differentiate user requested spaces
- make `SpatialReferences` standard spaces class attribute private

ENH: Add cache to SpatialReferences

---

niworkflows/utils/spaces.py

while progressing in https://github.com/poldracklab/fmriprep/pull/1955, we find ourselves extending the queries that i believe the `get_` helper methods were trying to solve. This PR improves the capabilities of `Spaces` querying for standard spaces.
I've only updated one get method for feedback, and if this looks alright, we can extend this to the others.

enh: standard space querying

---

niworkflows/utils/spaces.py
niworkflows/utils/tests/test_spaces.py

to add support for poldracklab/fmriprep#1979
This adds a `checkpoint()` call in `OutputReferencesAction` when the flag attached to the action is used with no arguments.

ENH: Revise SpatialReference caching for ease of use, accessibility

---

niworkflows/reports/core.py
niworkflows/reports/report.tpl

Addresses poldracklab/fmriprep#1991.

ENH: Display errors as summary/details elements

---

niworkflows/interfaces/images.py
niworkflows/interfaces/tests/test_images.py

This is a follow-up to #365. We were running into the case where `valid_qform` was `False`, and thus `qform` was an unbound variable, but trying to compare the new qform to the old qform.
This bug was introduced in 92e63fe, first released in 0.10.3. As this was included in fMRIPrep as of https://github.com/poldracklab/fmriprep/commit/b6d1e51bfc474602adaa37af6705856286b9735d, this bug is expected to affect versions 1.5.0-20.0.0 of fMRIPrep.
Fixes #465.

FIX: Check for valid qform before calculating change

---

.circleci/config.yml
Dockerfile
docker/files/nipype.cfg
niworkflows/func/tests/test_util.py
niworkflows/func/util.py
niworkflows/utils/misc.py
niworkflows/utils/tests/test_misc.py

This maintenance PR addresses several issues of the `test_masks` build in CircleCI:

MAINT: Fix test_masks

---

niworkflows/reports/core.py
niworkflows/reports/figures.json
niworkflows/reports/tests/test_core.py

supercedes #479 
addresses poldracklab/fmriprep#2033

[FIX] Add CE agent to output figure filename templates

---

niworkflows/reports/figures.json

two items that I thought should be changed:
- contrast -> ceagent in the anatomical `default_path_patterns`
- remove _bold from echo pattern, (I'm not sure what the original intention of the pattern was, but the double backslash does not [appear to match a reasonable string](https://regex101.com/r/UQROec/1), and echo is not required to be the last key-value pair in the [`default_path_patterns`](https://github.com/nipreps/niworkflows/blob/bfffaf8ea8e6fe1615be4a24089a5d750bd6e024/niworkflows/reports/figures.json#L116))

[FIX] update naming patterns in figures.json

---

niworkflows/interfaces/cifti.py

Go one step beyond #477 and ensures volumetric output in LAS orientation.

ENH: Ensure subcortical CIFTI is in LAS orientation

---

.circleci/config.yml
.travis.yml
setup.cfg

Addresses #486.
Some mentions to python 3.5 still remain:
```
$ find . -name "*.py" -exec grep -H "35" {} \;
./niworkflows/reports/core.py:        # PY35: Sorted config dict for consistent behavior
./niworkflows/reports/core.py:                # PY35: Coerce to str to pacify os.* functions that don't take Paths until 3.6
./niworkflows/utils/misc.py:    for f in os.scandir(path):  # switch to context manager when py35 dropped
```

MAINT: Drop Python 3.5

---

.circleci/config.yml

Since migrating to the nipreps organization, we haven't been pushing images to dockerhub
https://hub.docker.com/r/nipreps/niworkflows/tags

MAINT: Push docker image to docker hub

---

niworkflows/interfaces/bids.py
niworkflows/interfaces/tests/test_bids.py

Adds `data_dtype` option to `DerivativesDataSink` to allow coercing data into desired dtypes.
Inspired by poldracklab/fmriprep#2001

ENH: Add option to change data dtype

---

niworkflows/interfaces/bids.py
niworkflows/utils/spaces.py
niworkflows/utils/tests/test_spaces.py

Sets the default value of volumetric references resolution to native.
Originally discussed in https://github.com/nipreps/niworkflows/pull/457#discussion_r375510227, looks it is needed.
Addresses poldracklab/fmriprep#2060 ~~https://github.com/poldracklab/fmriprep/issues/2000~~

ENH: Make default native resolution explicit

---

niworkflows/interfaces/bids.py

in fmriprep, `source_file` can be a non-existing file in the case of a multi-echo dataset.
this improves the fault tolerance of the interface when a problem arises fetching the datatype of the source file

FIX: gracefully handle problems when loading source file

---

niworkflows/anat/ants.py

reverts #496. 
Actual problem in https://github.com/poldracklab/fmriprep/issues/2061 lies within smriprep / fmriprep's connections.

REVERT: N4-only workflow connections

---

niworkflows/interfaces/nibabel.py
niworkflows/interfaces/tests/test_nibabel.py

per suggestion [here](https://github.com/nipreps/dmriprep/pull/77)

ENH: Add nibabel-based split and merge interfaces

---

niworkflows/interfaces/images.py
niworkflows/utils/images.py
niworkflows/utils/tests/test_images.py

Revise this buggy function with a more appropriate implementation. Issues addressed:
Resolves: #499

FIX: Better generalization and renaming+relocation in the API of ``extract_wm``

---

niworkflows/interfaces/nibabel.py

Addresses an oversight in #489 .

FIX: Merge/SplitSeries write to path of input image, instead of cwd

---

codecov.yml

Removes the "project" target from comments in PRs because the segregated
testing of niworkflows (masks, pytests, reportlets, ...) makes almost
all PRs to be under a decent project threshold (and hence show up as
failed).

MAINT: Add ``codecov.yml`` config file to reduce noise in PRs

---

niworkflows/utils/misc.py
niworkflows/utils/tests/test_misc.py

This adds a missing piece of #505, the ability to set and check non-standard license location (anywhere that isn't `$FREESURFER_HOME/license.txt`)

ENH: add ability to set license

---

niworkflows/interfaces/bids.py
niworkflows/utils/misc.py
setup.cfg

Quickfix for two problems:
```Python
>>> "some.file.svg".rstrip(".gz")
'some.file.sv'
```
This PR uses a regexp to ensure this is not occurring. Also, it ~~fixes ``niworkflows.utils.misc.splitext`` for the same issue.~~ just adds a couple of doctests to better cover that function.

FIX: Two minor amends to #507

---

setup.cfg

~A new release of skimage is breaking or tests. Also,~ 
Remove leftovers of dependencies pinned for Python < 3.6 (#486)

MAINT: Remove conditional dependencies on Python <3.6

---

.circleci/config.yml
.travis.yml

imagecodecs has kind of forced our hand with regard to testing lower version pip/setuptools. To handle manylinux2010, we need pip 19+.
Also cleaned up the `.travis.yml` based on config validation, adding an `os` entry, dropping the deprecated `sudo`, and renaming `matrix` to `jobs`.

CI: Fix skimage 0.17-induced failures

---

niworkflows/interfaces/bids.py

brought to attention in https://github.com/poldracklab/fmriprep/issues/2142

FIX: Ensure dataobj datatype is altered

---

niworkflows/interfaces/bids.py
niworkflows/interfaces/tests/test_bids.py

Supplements #527; Non-integer data initialization wasn't being exercised by the tests, and was leading to:
```
TypeError: 'numpy.dtype' object is not callable
```

FIX: Non-integer data coercion initialization

---

MANIFEST.in
pyproject.toml
setup.cfg
setup.py

Trying to improve the comments to make it clearer why `setup.py`/`setup.cfg` are written the way they are.
In #507, the LICENSE was removed from the sdist, which seems like a mistake to me. This is available with the `license_file` metadata, which setuptools begins to respect in 40.8.0. This only needs to be respected for building sdists, though, so the minimum setuptools to install remains unchanged.
I also think it's a mistake to remove `conftest.py`. Tests are first-class citizens in niworkflows, and should work from an installed copy using `pytest --pyargs niworkflows`. Removing `conftest.py` in sdists will modify the behavior of tests depending on the installation method.

MNT: Update comments, minimum versions for setup requirements

---

niworkflows/interfaces/images.py
niworkflows/utils/images.py
niworkflows/utils/tests/test_images.py

This is a replacement for ANTs' ``ResampleImageBySpacing`` with a more
rigorous handling of NIfTI x-form headers.
cc/ @eilidhmacnicol
This may also be useful to @mgxd in the adaptation of antsBrainExtraction to infants.
@effigies' pair of eyes will be very much appreciated, as this new interface plays quite a bit with nibabel's image objects.

ENH: Add a pure-Python interface to resample to specific resolutions

---

.circleci/config.yml
docs/requirements.txt
niworkflows/func/tests/test_util.py
niworkflows/func/util.py
setup.cfg

Replaces the template's binary mask with a probabilistic map.
The workflow for EPI brain-extraction utilizes an atlas-based approach in its initialization. Before this PR, the template's mask is binary. The intention is to minimize numerical instability of edge voxels due to the resampling of the binary mask (i.e., when _moving the atlas' brain mask on to the subject space_). With this PR, the binarization occurs later and the risk of having a voxel whose value varies between runs (due to the minimal but existing variability introduced by the ants registration process) is much lower.
See #476

ENH: Numerical stability of EPI brain-masks using probabilistic prior

---

.circleci/config.yml
niworkflows/anat/ants.py
niworkflows/func/tests/test_util.py
niworkflows/func/util.py
niworkflows/interfaces/registration.py
niworkflows/utils/connections.py
niworkflows/utils/misc.py

Closes #399. 
This PR allows `bold_reference_wf` to accept multiple BOLD and/or SBRef files, under the assumption that multiple files reflect multiple echoes from the same run. It currently just selects the first image from each for use, but could be extended to use information from multiple echoes for reference image generation.
The workflow still returns just one BOLD file, since a number of workflows take the BOLD file stored in the output node as their inputs, and they are not currently set up to work with multi-echo data. To that end I also added a function to `utils.misc` to select the first item in a list.
These changes shouldn't impact behavior at all, but there will need to be a corresponding PR in fMRIPrep in order to feed multi-echo data and SBRefs into the reference image …

ENH: Allow bold_reference_wf to accept multiple EPIs/SBRefs

---

niworkflows/utils/misc.py
niworkflows/utils/tests/test_misc.py

#533 broke API mid-series. This restores it while also not modifying the environment.
Target: 1.2.6.

FIX: Restore and deprecate license argument to check_valid_fs_license

---

niworkflows/interfaces/cifti.py

Since outputs would change, this PR targets `1.3.0`

FIX: Avoid diverting CIFTI dtype from original BOLD

---

niworkflows/interfaces/images.py
niworkflows/interfaces/tests/test_images.py

closes [smriprep/issues/198](https://github.com/poldracklab/smriprep/issues/198).
Conform resizes voxels if the difference between zooms is at least 0.01mm. Freesurfer's tolerance is [0.001 mm](https://github.com/freesurfer/freesurfer/blob/4db941ef298c0ac5fb78c29fd0e95571ac363e16/mri_robust_register/MultiRegistration.cpp#L258), which throws `mri_robust_template` off if 0.01>difference>0.001.
This PR fixes the zooms in that case.
I have added tests, but haven't tried it with real data in smriprep. @effigies, @oesteban, could you please take a look whether this makes sense, then I'll also run smriprep with real data.

Conform fix zooms

---

niworkflows/reports/core.py
niworkflows/utils/misc.py

Closes #486 
context manager change context: https://bugs.python.org/issue25994

RF: update to py36+

---

niworkflows/interfaces/bids.py

Changes to allow processing dataset without T1w series if `--anat_derivatives` are provided.
See https://github.com/poldracklab/fmriprep/pull/2201

fix: skip t1w file existence check if anat_derivatives are provided

---

niworkflows/utils/images.py
niworkflows/viz/utils.py

While nilearn/nilearn#2525 is considered, this PR advances the generation of mosaics after aligning the affine matrix of the data with the cardinal axes. This should overcome the glitches when nilearn is requested to plot contours and the mask for the ROI has voxels that only partially intersect with the visualization plane.
Resolves: #542.
References: #281, #304.
Depends: #543.

FIX: Segmentation plots aligned with cardinal axes

---

niworkflows/interfaces/bids.py

This change permits DerivativesDataSink to take multiple files in order to extract entities. It keeps common entities and discards differing entities.
Doctest included to demonstrate.
Alternative to nipreps/smriprep#223.

RF: Enable DerivativesDataSink to take multiple source files to derive entities

---

setup.cfg

See #548 for the fix in the development branch.

FIX: Pin PyBIDS < 0.11 (and TemplateFlow < 0.6.3) only on the 1.2.x series.

---

niworkflows/interfaces/images.py
niworkflows/utils/images.py

Resampling (up- or down-) typically requires a gussian smoothing to be
run before, so that outliers are not introduced (esp. when
downsampling).
This PR adds this option, relying on scipy.
This is the first element of a series of PRs deconstructing #506 into digestible, independent bits.

ENH: Add ``smooth`` input to ``RegridToZooms``

---

niworkflows/interfaces/fixes.py
niworkflows/interfaces/itk.py

First step in addressing #553.
The current trait is:
```Python
transforms = traits.Either(
InputMultiPath(File(exists=True)),
"identity",
argstr="%s",
mandatory=True,
desc="transform files: will be applied in reverse order. For "
"example, the last specified transform will be applied first.",
) 
```
This will deserve its own nipype patch, but let's not stand on ceremony, there.

FIX: Patch ApplyTransforms spec to permit identity in a chain

---

niworkflows/interfaces/plotting.py
niworkflows/tests/test_confounds.py
niworkflows/viz/plots.py

This PR adds a ``columns`` argument to the interface and underlying function so that _fMRIPrep_ can select what confounds will be used to estimate the correlations.
The PR also minimizes to 20 (it was 70!) the number of signals that are plotted.
References: poldracklab/fmriprep#1746
References: https://github.com/poldracklab/fmriprep/issues/2245#issuecomment-682618147

FIX: Improved control over correlations plot

---

niworkflows/interfaces/utils.py

A minimal change to the capitalization of the metadata dictionary key.
Resolves: #400.

FIX: AROMA metadata ``CsfFraction`` -> ``CSFFraction``

---

niworkflows/viz/utils.py

The function that calculates the bounding box (and the cuts) to be
represented in reportlets has default thresholds thought out for brain
masks.
When passed a white-matter mask, these thresholds could yield only one
cut (below the required number of cuts).
This patch checkes that the number of cuts are sufficient in all the
cutting planes.
Resolves: #559.

FIX: Reportlets would crash in edge condition

---

niworkflows/anat/ants.py

This PR introduces changes to better handle the copying of headers within the workflow, which is a potential source for nipreps/smriprep#127, and addresses some problems that surface when the ATROPOS refinement step fails (nipreps/smriprep#125).
This refactor could be considered a preliminary work on #531.

FIX: Revision of ``antsBrainExtraction``, better handling edge cases

---

niworkflows/interfaces/images.py

This is a minor improvement to reports that can enter the 20.2.x series of fMRIPrep, so targeting 1.3.x series of niworkflows.
This determines the spatial units of the affine, assuming mm if not coded. I've verified that `transforms3d.axangles.mat2axangle` returns angles in radians.
Addresses nipreps/fmriprep#2287.

ENH: Add units to qform overwrite report

---

niworkflows/interfaces/mni.py

Since templateflow templates are not required to have `<res>` identifiers, there should be a way to disable searching for one.
EDIT: This is a bit of a hacky solution, especially since `template_resolution` is deprecated. Open to other suggestions.

FIX: Allow omission of <res> for template normalization

---

.zenodo.json
LICENSE
niworkflows/__about__.py
setup.cfg

(see nipreps/fmriprep#2325 for the rationale behind this move)

MAINT: Relicense from BSD-3-Clause to Apache 2.0

---

niworkflows/interfaces/utils.py

Hi guys,
I really like `niworkflows`! I use it to write simple workflows of my own.
For example, I collect MT-weighted images at 7T with an extremely high in-plane resolution of .35 mm. The thickness of the field-of-view, however is only 44 slices, which makes the images not ridiculously big. However, when I registered them to T1w-space and used  `GenerateSamplingReference` to transform them there in their own, native resolution, I noticed that the reference image had 350 slices and the reference image contained 148 million voxels, leading to memory problems.
I think this happened because there is a little bug in the `_gen_ref`-method, that actually does not use the FOV-mask to calculate where to cut off the reference image, but it uses the fixed image that defines the reference space. …

FIX: Use the mask to calculate FOV rather than the fixed image in ` GenerateSamplingReference`

---

niworkflows/interfaces/plotting.py

Introduced in 1.2.0rc2. in `maint/1.2.x`, to be merged into `maint/1.3.x` and `master` on completion.
Identified by GitHub user @hrswearingen in https://github.com/poldracklab/mriqc/issues/867.

FIX: Check for in_segm input, not seg_file (typo)

---

.github/workflows/pythonpackage.yml
Dockerfile
setup.cfg

As noted in other discussions, setuptools is aiming to be an installation backend, not an installer, and has no plans to implement various installation PEPs, such as respecting the `PythonRequires` metadata exposed by PyPI.
Therefore I think the recommended installation method needs to be pip. Since we distribute sdists and wheels, we should continue to test those, and those are built with `setuptools` and `wheel`, but we do not need to test against old versions.
We may want to test against old versions of `pip` again, but I think after a year or two of using `pyproject.toml`, we're pretty comfortable that pip can fetch installation dependencies as needed for this project and its dependencies.

MNT: Drop Python 3.6, test setuptools builds, pip installations 

---

.github/workflows/pythonpackage.yml
Dockerfile
setup.cfg

See https://github.com/nipreps/niworkflows/issues/595 for context

PIN: svgutils to previous versions

---

setup.cfg

A temporary solution to the svgutils problem. With 0.3.3 we will need to revise this again https://github.com/nipreps/niworkflows/issues/595#issuecomment-756129457.
Resolves: #595 .

FIX: Change in *svgutils*' API on 0.3.2 breaks reportlets

---

niworkflows/interfaces/bold.py
niworkflows/interfaces/images.py

This PR introduces two changes into ``RobustAverage``:
- Replaces the global signal calculation - for very skewed datasets, ``np.median(data, axis=(0,1,2))`` very easily contained zeros. In this PR, that is replaced by two steps: 1) removing potential outliers by clipping percentiles; and 2) replacing median by mean.
- Compensation for global signal is done before HMC, with the hope of aiding correction and interpolation.
Fixes the tests currently broken on master.

FIX: Address issues with ``RobustAverage`` global signal measurement

---

.circleci/config.yml

This dataset is added to set the ground for testing the new reference
calculation workflow (#601).
Additionally, I will upload derivatives from fMRIPrep with the objective
of setting up some regressions tests for nipreps/fmriprep#2307.
Related: #601, nipreps/fmriprep#2307.

MAINT: Add DS030 dataset, with clipped (55 timepoints) BOLD data

---

.circleci/config.yml

Currently:
```Shell
$ time git clone https://github.com/nipreps/niworkflows.git           
Cloning into 'niworkflows'...
remote: Enumerating objects: 17457, done.
remote: Counting objects: 100% (17457/17457), done.
remote: Compressing objects: 100% (2299/2299), done.
remote: Total 890088 (delta 15964), reused 16084 (delta 14654), pack-reused 872631
Receiving objects: 100% (890088/890088), 1.14 GiB | 8.75 MiB/s, done.
Resolving deltas: 100% (801905/801905), done.
git clone https://github.com/nipreps/niworkflows.git  225.60s user 34.76s system 128% cpu 3:22.09 total
$ du -sh niworkflows 
1.3G	niworkflows
```
Just checking out master:
```Shell
$ time git clone --single-branch https://github.com/nipreps/niworkflows.git
Cloning into 'niworkflows'...
remote: Enumerating objects: 70, done. …
```

MNT: Drop gh-pages history, reducing repository size

---

niworkflows/func/util.py
niworkflows/interfaces/images.py

Currently, the `init_bold_reference_wf` is failing at https://github.com/nipreps/niworkflows/blob/fa56d3048f6a9972f4008ad32f40088e4aaba94b/niworkflows/func/util.py#L241-L245
~~This PR adds a new input `sbref_file` to `RobustAverage`.~~
This PR sets the merged sbref_file as the in_file and leverages existing logic to handle 3D inputs.

FIX: Readd sbref_file input to reference volume interface

---

Dockerfile
niworkflows/viz/utils.py

svgo 2.x dropped support for CLI plugin alteration.
We could generate a JSON config with this option, but
the changes are so miniscule we can likely just drop this flag.
This PR also pins the svgo version in the Dockerfile to the 2.x series.

FIX: Purge removed `--disable` flag from svgo call

---

Dockerfile
niworkflows/interfaces/registration.py
niworkflows/interfaces/tests/test_registration.py
niworkflows/viz/utils.py

Fixes #628. At least partially. If we're splitting and concatenating 900MB of data, it seems plausible we could double our usage to 1.8GB. Maybe should call it 2GB to be safe?

FIX: Limit memory usage in EstimateReferenceImage

---

niworkflows/workflows/epi/refmap.py

Just adds to the output node one additional output that is anyways produced.

ENH: Expose the output of the ``ValidateImage`` node as an output in EPI reference workflow

---

niworkflows/reports/default.yml

Brings the specification from dMRIPrep, covering the new SDCFlows capabilities.

ENH: Update visual report specification with fieldmaps

---

niworkflows/interfaces/nibabel.py

When testing this new interface in nibabies, an image with shape (x, y, z, 1) caused a crash. The problematic line was 
`denoised = ndimage.median_filter(data, footprint=ball(3))`, which may be currently limiting to only 3D files.
This PR squeezes whatever input we get and adds a quick assertion to verify the image is 3D. We may want to revisit this if there are plans to also run on 4D files.

FIX: Ensure IntensityClip input is a 3D file

---

niworkflows/viz/utils.py

Changes the mask outline from blue to red, for increased contrast.

FIX: Improve mask contour visibility

---

Dockerfile
niworkflows/interfaces/utils.py

With the most recent `pandas` version, I am getting the following warning:
```
/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utils.py:896: FutureWarning: In a future version of pandas all arguments of read_csv except for the argument 'filepath_or_buffer' will be keyword-only
```
I have attached the required change to avoid it.

[FIX] `pandas` warning about use of keyword arguments

---

niworkflows/interfaces/freesurfer.py

- As proposed by @effigies in nipy/nipype#3361

[FIX] `FSDetectInputs` mutually exclusive options for `ReconAll`

---

niworkflows/interfaces/bids.py
niworkflows/interfaces/tests/test_bids.py

As per https://github.com/nipreps/niworkflows/pull/573#issuecomment-893510319

FIX: DerivativesDataSink warning when it has multiple source files [backport #573]

---

niworkflows/interfaces/reportlets/base.py
niworkflows/interfaces/reportlets/registration.py
niworkflows/viz/utils.py

Follows #544 
Allows `SimpleBeforeAfter` reports to rotate images with respect to the cardinal axes. This is motivated in the context of SDC correction, to give a clearer look at the distortions.

ENH: Allow plotting of image rotated to cardinal axes

---

niworkflows/interfaces/bids.py
niworkflows/interfaces/tests/test_bids.py

Test fails prior to fix. Required updating checksums.
This will fix nipreps/fmriprep#2507 and should be considered high priority.

FIX: Set slope and intercept to 1/0 if not otherwise provided

---

.zenodo.json
CHANGES.rst
tools/update_changes.sh

Needed for a 20.2.4 release of fMRIPrep.
Added @HippocampusGirl and @Gilles86 to Zenodo for their contributions, though I think Gilles's contribution was a bit ago...

REL: 1.3.5

---

.github/workflows/docs-build-update.yml

Fixes a bad condition that averted the push of the new docs (#656)

DOC: Ensure commits to master trigger a documentation update

---

niworkflows/viz/plots.py

This PR is a mix of fixes and enhancements to `viz.plot_carpet`. Most of the enhancements are based on personal preference so they can be dropped if desired.
**Fixes**
- Legend should now show up if `legend = True`
+ The legend argument was not getting passed from `carpet_plot()` to `_carpet()`
- Title should now show up if `title` argument is specified
**Enhancements**
- The `nskip` argument should now work for NIfTI inputs
+ Looks like it's trivial to implement this for CIFTI as well, but I don't use them, so I didn't touch it
- Tick formatting
+ If the xticks are frame numbers, then they will be printed as integers instead of decimals
+ Xticks now use the default font size
+ This prevents a clash with user-defined matplotlib configuration
- The input data can now be a nibabel-image. A …

ENH: carpet plot tweaks

---

pyproject.toml

Any objection to these configurations? By using a higher line length and not changing all quotes to double-quote, we can keep the sheer amount of rewrites down.
Would like to bring this over to fMRIPrep and the other tools, too.

MNT: Configure black to avoid excessive rewriting

---

setup.cfg

This still ensures we don't get 3.3.0, but allows us to go gracefully up minor version releases of MPL.
Closes #667,

MNT: Relax matplotlib constraint

---

niworkflows/anat/ants.py
niworkflows/utils/images.py
niworkflows/workflows/epi/refmap.py
setup.cfg

Addressing #611, this PR 1) adds a function to determine bspline grid using a ratio of the number of slices in each dimension, and 2) adds logic to various workflows so that this might be used with rodents by updating the N4 parameters.  Not to say that the function can't be used with non-rodent images, but it hasn't been tested as such. 
There are other workflows that call `N4BiasFieldCorrection`, but they are unlikely to be used by NiRodents/fprodents because there are already rodent alternatives or because they would require more changes and would probably benefit from a rodent-specific workflow.

ENH: add rodent-specific adaption for B-spline

---

niworkflows/func/util.py

This makes correctly processing multi-echo data more standardized. This makes xform-synchronized versions of the original echos available to downstream nodes through the `outputnode.all_bold_files` instead of having to call `val_bold.out_file`.

ENH: Return all bold files from init_bold_reference_wf

---

niworkflows/interfaces/tests/test_images.py

We know that our method runs faster and uses less memory than nilearn's, so let's take the fastest one and just ensure that we don't lose equivalence.

TEST: Drop excessively long interface equivalence tests

---

niworkflows/interfaces/morphology.py
niworkflows/interfaces/plotting.py
niworkflows/interfaces/tests/test_morphology.py

This pull request augments the existing carpet plot by adding to it the signals from the voxels at the edge of the brain.
The new code contains both the computation of the crown mask and its insertion in the carpet plot.
Furthermore, an interface computing the crown mask has been added in the purpose of being used in fMRIPrep and MRIQC.
Last, a legend of the colorbar separating regions in the carpet plot has been adding therefore closing nipreps/mriqc#870.
IMPORTANT ! : This piece of code depends on the change in the fMRIprep repository commited under the pull request https://github.com/nipreps/fmriprep/pull/2621 and on the change in the MRIQC repository under the pull request nipreps/mriqc#968

ENH: Initiate a module of nipype interfaces for mathematical morphology

---

niworkflows/interfaces/plotting.py
niworkflows/interfaces/tests/test_plotting.py
niworkflows/tests/test_viz.py
niworkflows/utils/timeseries.py
niworkflows/viz/plots.py

Several minor improvements to carpets:
NIfTI with segments:
NIfTI without segments:
CIFTI2:

ENH: Miscellaneous improvements to carpetplot

---

niworkflows/tests/test_viz.py
niworkflows/viz/plots.py

Instead of printing labels on the left, this PR adds a legend beneath the carpet chunks. Hopefully closing the very much-needed overhaul of carpet plots.

ENH: Add a legend to carpet plots with more than one segment

---

niworkflows/interfaces/bids.py

If you have write permissions in a directory but not on a file (main context: locked git-annex files), then you can get a situation where trying to write without first deleting will fail while deleting and rewriting will succeed.

FIX: Unlink destination files before saving derivative

---

Dockerfile
niworkflows/interfaces/bids.py
niworkflows/utils/misc.py
setup.cfg

Closes #694.
Merging into `maint/1.4.x` which will get merged into `maint/1.5.x` and then `master`.
I don't think we need an immediate 1.4.x release, since only fMRIPrep 21.0.x depends on it, which we distribute with Python 3.8.

FIX: Add unlink() with missing_ok for Python 3.7

---

.github/workflows/pythonpackage.yml
docs/conf.py
niworkflows/conftest.py
niworkflows/interfaces/bids.py
niworkflows/interfaces/freesurfer.py
niworkflows/interfaces/tests/test_bids.py
niworkflows/interfaces/tests/test_images.py
niworkflows/testing.py
niworkflows/tests/conftest.py
niworkflows/tests/test_registration.py
niworkflows/tests/test_segmentation.py
niworkflows/utils/bids.py
niworkflows/utils/tests/test_misc.py
niworkflows/workflows/epi/tests/test_refmap.py
setup.cfg

We have a kind of silly setup where we make sure that we can build the package across Python versions and get the correct version out, but we don't run even basic tests on these installations, meaning we miss things like #694.
This builds on #695, but I don't want to block that going in while I play with GitHub actions.

CI: Install package across Python versions and run pytest 

---

niworkflows/interfaces/bids.py
niworkflows/interfaces/tests/test_bids.py
niworkflows/tests/test_viz.py
niworkflows/utils/bids.py
setup.cfg

* fMRIPlot tests use `os.path.join(save_artifacts, ...)` which doesn't work when `save_artifacts` is a bool.
* PyBIDS 0.15 (released today) breaks tests that assume zero-padding on run entities is stripped. Let's just require 0.15+
* While we're at it, add some dots to some extensions.

FIX: Test failures

---

niworkflows/utils/bids.py

A slight alteration to provide session level control.

ENH: Add optional session filter when collecting data

---

niworkflows/interfaces/bids.py

FIX: Use copy function that does not preserve mtime when creating fsaverage directories

---

niworkflows/interfaces/norm.py

Catches cases where the brain mask is under the `label` entity (i.e. UNCInfant).
This should address the problem in nipreps/nibabies#187

FIX: Alternate query for template brain mask

---

niworkflows/interfaces/nibabel.py
niworkflows/interfaces/tests/test_nibabel.py

This should help clear up the error found in https://github.com/nipreps/fmriprep/issues/2706

ENH: Add `affine_tolerance` flag to `MergeSeries`

---

.circleci/config.yml

New branch, so we don't need to bump the cache numbers yet.

CI: Fallback to maintenance branch first

---

CHANGES.rst
Dockerfile
docs/conf.py
docs/requirements.txt

Prepare 1.6.0 release.
@mgxd Is there any reason we should include some of these fixes in 1.5.x? We could do a 1.5.5 release with the old miniconda image and a 1.6.0 with the new.

REL: 1.6.0

---

setup.cfg

Now that wslink / brainspace incompatibilities are merged and released.

MAINT: Remove pins that broke prerelease tests

---

setup.cfg

This pin should probably also go in nipype, as the [6.4.0 release notes](https://github.com/enthought/traits/releases/tag/6.4.0) indicate they're deprecating `Either` and changing the semantics of `Tuple`.

MNT: Pin traits < 6.4

---

niworkflows/interfaces/bids.py
niworkflows/interfaces/tests/test_bids.py

This addresses an issue that popped up in https://github.com/poldracklab/tacc-openneuro/issues/23 - with the FS7 migration, we should be aware that fsaverage directories generated from previous FS versions are incomplete and will lead to errors.
This proposes a new input, `minimum_fs_version`, which checks if the `<space>` directory includes newer files. If not, it will remove it and make a fresh copy.

ENH: Add `minimum_fs_version` input to handle outdated `fsaverage`s

---

.github/workflows/pythonpackage.yml

Since github actions does not yet support early, successful job termination(!), this required splitting the test/install into separate stable and pre-release jobs.

CI: Extract pip pre checks into separate, skippable job

---

niworkflows/interfaces/cifti.py
niworkflows/interfaces/tests/test_cifti.py

- Drops support for older, fsaverage/MNI152NLin2009cAsym style
- Reworks metadata to be BIDS compliant
- Adds typing hints
- Removes `surface_density` input, in favor of new `grayordinates` input
Since this includes breaking changes, upstream changes to the fmriprep / nibabies workflows will be needed.

Rework: GenerateCifti interface

---

niworkflows/interfaces/bids.py

While working on nipreps/smriprep#303, I found `--fast-track` would crash because we would attempt to save an input file to its same location. The datasink removes the target file before copying to avoid writing into a symlink, which means we lose the input.
I'm separately changing the workflow to ensure that datasinks are generally not created for unchanged files, but this seems safe in any event.

ENH: Allow DerivativesDataSink to handle output==input

---

.github/workflows/pythonpackage.yml

Addressing GitHub actions warning:
>  check_if_skip
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

CI: Drop set-output

---

niworkflows/interfaces/bids.py

Closes #757. I'm not sure how I should test this, given there is only one config file in niworkflows at the moment.
- Store the entity and filename config variables (currently stored as globals) as attributes in DerivativesDataSink. This will hopefully make it easier for other packages to build child classes from DerivativesDataSink, with their own config info.

REF: Store global variables as DerivativesDataSink attributes

---

niworkflows/viz/plots.py

Using `np.bool` has been deprecated since `numpy 1.20.0` and was removed with the most recent release. For more information, see <https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated>. The recommended alternative is to simply use the built-in `bool`. 
In this pull request, I apply the recommended alternative in one line.
```
Traceback (most recent call last):
File "/usr/local/miniconda/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 398, in run
runtime = self._run_interface(runtime)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/miniconda/lib/python3.11/site-packages/niworkflows/interfaces/plotting.py", line 177, in _run_interface
confounds_correlation_plot(
File …
```

Fix error for `np.bool` with `numpy 1.24.0`

---

.github/workflows/pythonpackage.yml

Also sets the branch to `**` for `push`. `*` does not match slashes, so maintenance branches have been excluded.

CI: Update GitHub actions from master

---

niworkflows/interfaces/tests/test_nibabel.py

Looks like we didn't really look at the `FutureWarning`s and `DeprecationWarning`s recently. We should've been seeing this for 6 months or so.
Easy fix.

FIX: Create test label images with realistic dtypes

---

.circleci/config.yml
Dockerfile

Docker builds are broken due to conda environment solving timing out (>2 hours).

MNT: Try bumping docker base to latest nipreps/miniconda

---

niworkflows/viz/utils.py

Supercedes https://github.com/nipreps/smriprep/pull/317

FIX: Coerce `MGHImage`s to `Nifti1Image`s when plotting

---

niworkflows/data/boldref-mni_registration_precise_000.json
niworkflows/data/boldref-mni_registration_precise_001.json
niworkflows/data/boldref-mni_registration_precise_002.json
niworkflows/data/boldref-mni_registration_testing_000.json
niworkflows/data/boldref-mni_registration_testing_001.json
niworkflows/data/boldref-mni_registration_testing_002.json
niworkflows/data/epi_atlasbased_brainmask.json
niworkflows/data/t1w-mni_registration_fast_000.json
niworkflows/data/t1w-mni_registration_precise_000.json
niworkflows/data/t1w-mni_registration_precise_001.json
niworkflows/data/t1w-mni_registration_precise_002.json
niworkflows/data/t1w-mni_registration_testing_000.json
niworkflows/data/t1w-mni_registration_testing_001.json
niworkflows/data/t1w-mni_registration_testing_002.json

`--use-estimate-learning-rate-once` was removed in https://github.com/ANTsX/ANTs/pull/1411 (released v2.4.1). It seems it has had no effect for some time (I think since v2.0.0).

FIX: Remove unused ANTs parameter that was removed in 2.4.1

---

niworkflows/viz/utils.py

This addresses https://github.com/poldracklab/tacc-openneuro/issues/40.
It's a rare case, but if the series can be 3D, we should be handle it.

FIX: Handle plotting only one MELODIC component

---

niworkflows/viz/plots.py

Finally got irritated enough to figure out why the confound order went nuts in the correlation plot. Using set, there are no order guarantees. We can get deduplication with `dict.from_keys()` instead, which produces a set-like dict with values all `None`. We can then just `list()` on the dict to get the keys back in the order they were initially passed.

FIX: Restore confound order in correlation plot

---

niworkflows/viz/plots.py

Fixes current failures in fMRIPrep.

FIX: Avoid sorting carpetplot rows when decimated ROIs have one voxel

---

niworkflows/data/nipreps.json
niworkflows/interfaces/bids.py
niworkflows/reports/core.py
niworkflows/reports/tests/test_core.py

Closes #776.
- Convert `DerivativesDataSink._config_entities` and `DerivativesDataSink._file_patterns` into a `bids.layout.Config` object, then feed this Config into `parse_file_entities` (along with the default `bids` and `derivatives` ones) in order to extract custom entities from the `source_file`.

Pass custom configuration into DerivativesDataSink entity parser

---

niworkflows/viz/plots.py

Relying on high-resolution fasttrack derivatives has led to missing cases where carpetplot ROIs are degenerate. Most likely the dWM/dCSF.

FIX: Check for empty segments in plot_carpet

---

niworkflows/interfaces/bids.py
niworkflows/utils/bids.py

ENH: Allow passing a ``database_path`` to create a ``BIDSLayout``

---

niworkflows/interfaces/images.py

Occasionally, the `-twopass` option in AFNI's 3dVolReg overshoots the mark, particularly when two volumes are already quite close in space (e.g. when pepolar "blip" images are acquired immediately after each other with the same slice package, but with the phase encoding direction reversed). 
[When using `RobustAverage` to merge two blip volumes ](https://github.com/nipreps/sdcflows/blob/0c497abbd9fa5b7a6f3f759d45ad7c94949b79be/sdcflows/workflows/fit/pepolar.py#L145), the second image is displaced >10mm on the second pass, giving a terrible average, while with only one pass the displacement is ~1mm. 
This PR gives the option to bypass the second pass and stick to just one. The default is `True` for backwards compatibility. WDYT?

fix: add option to bypass twopass in AFNI RobustAverage

---

niworkflows/interfaces/reportlets/__init__.py
niworkflows/viz/__init__.py

This is only to help our most vigilant of user, as it won't add noise unless Python Development Mode is enabled.

MNT: Add PendingDeprecationWarning to nireports modules

---

docs/requirements.txt
niworkflows/interfaces/conftest.py
niworkflows/interfaces/surf.py
niworkflows/interfaces/workbench.py
niworkflows/utils/bids.py

Bring in interfaces introduced in https://github.com/nipreps/fmriprep/pull/3011

ENH: Port GIFTI/CIFTI interfaces from fMRIPrep

---

niworkflows/interfaces/cifti.py
niworkflows/interfaces/tests/test_cifti.py

This "fix" resolves an inconsistency with HCP CIFTI-2 generation. The metadata of our CIFTIs should still have been correctly generated.
Closes #814.

FIX: Generate CIFTI volume structure indices in column-major order

---

docs/api.rst
docs/conf.py
docs/requirements.txt
niworkflows/__init__.py
niworkflows/anat/ants.py
niworkflows/conftest.py
niworkflows/data/__init__.py
niworkflows/func/util.py
niworkflows/interfaces/bids.py
niworkflows/interfaces/norm.py
niworkflows/interfaces/tests/data/__init__.py
niworkflows/interfaces/tests/test_itk.py
niworkflows/interfaces/tests/test_plotting.py
niworkflows/reports/core.py
niworkflows/reports/tests/test_core.py
niworkflows/tests/conftest.py
niworkflows/tests/data/__init__.py
niworkflows/tests/test_registration.py
niworkflows/utils/misc.py
pyproject.toml

Fixes current test failures from using a deprecated `importlib.resources` API.
Expanded on an `ExitStack`-based load function that @mgxd used in one of these projects into a class that provides flexible access to package data with readable, unzipped, and cached access methods.
We have the following loaders:
* `niworkflows.load_resource` - Generic, can get anything from anywhere
* `niworkflows.data.load` - Primary access point for package data
* `niworkflows.tests.data.load_test_data` - Convenience for tests
* `niworkflows.interfaces.tests.data.load_test_data` - Convenience for interface tests
I would like to figure out how to bundle the library in a zip to actually test that this works when installed that way, but for this PR the goal is to make it easy to think about and select whether …

ENH: Add data loader class, install at root and data modules

---

niworkflows/interfaces/norm.py
niworkflows/interfaces/tests/test_norm.py

Messed this up in #816 (008277f4522b466aa51fb5cfa80a607760d53cd3). Changing to a more descriptive iterator variable name.

FIX: Test names of paths when calling path.iterdir()

---

niworkflows/interfaces/bids.py

Fixes nipreps/fmriprep#3055.
The goal of matching source dtypes for boldrefs was for straightforward comparisons, but because we say a file that is `int16` on-disk must be coerced to `int16`, we lose the scaling that makes that possible. I don't really want to try to handle all of the cases, as we already have a pretty baroque typing setup. I think the simplest thing is just to say that these are `float32`s.

FIX: Save boldrefs as float32

---

niworkflows/interfaces/bids.py
niworkflows/utils/bids.py

This PR adds PET support to the BIDS grabber in niworkflows, and addresses issue https://github.com/nipreps/niworkflows/issues/822#issue-1869149672 and mentioned here https://github.com/openneuropet/petdeface/pull/13

ENH: add PET support to niworkflows

---

niworkflows/viz/plots.py
niworkflows/viz/utils.py

The new release removes `Tick.label` and replaces it with `Tick.label1`. See https://github.com/matplotlib/matplotlib/pull/23463

FIX:Compatibility with matplotlib 3.8.0

---

.circleci/config.yml
pyproject.toml
setup.cfg
setup.py

Latest PyPI upload for the LTS branch failed because twine was incompatible with urllib3 in the build environment.
This PR switches to `pipx`, which is less susceptible to incompatible environments, and uses it to run `build` and `twine`, simplifying things significantly.
During testing, got an error over our use of `license_file` instead of `license_files`, so I updated that and the minimum setuptools versions. Added `build-backend` by default, which then led to needing to add versioneer to the build requires.
Current tests use all of the changes except deploy, so if checks are green, this should be safe to merge.

FIX: Build config and CI

---

.circleci/config.yml
CHANGES.rst

REL: 1.9.0

---

.github/workflows/pythonpackage.yml
pyproject.toml

Now that templateflow is out, this should be fine.

MNT: Test Python 3.12 support

---

docs/sphinxext/github.py
niworkflows/tests/conftest.py
niworkflows/viz/utils.py

* remove no-ops (`return` at end of function and `x = x`)
* use list comprehensions
* `utcnow()` → `now(tz=timezone.utc)`
From https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow:
> **Warning:** Because naive `datetime` objects are treated by many `datetime` methods as local times, it is preferred to use aware datetimes to represent times in UTC. As such, the recommended way to create an object representing the current time in UTC is by calling `datetime.now(timezone.utc)`.
> 
> _Deprecated since version 3.12:_ Use [`datetime.now()`](https://docs.python.org/3/library/datetime.html#datetime.datetime.now) with [`UTC`](https://docs.python.org/3/library/datetime.html#datetime.UTC) instead.

STY: Assorted refurb suggestions

---

niworkflows/interfaces/bids.py
niworkflows/utils/bids.py

This PR adds DWI to the queriable suffixes, and also opens a possibility to modify the default queries.

FIX: Add DWI to the default queries of BIDS querying

---

niworkflows/workflows/epi/refmap.py

I believe there is a typo in the docstring (introduced by #636)

DOC: Fix typo in `refmap.py`

---

niworkflows/data/nipreps.json
niworkflows/interfaces/bids.py
niworkflows/utils/bids.py
niworkflows/utils/spaces.py

Closes #838.
- Add "asl" to list of non-standard spaces.
- Add "asl" field to data collection function (`collect_data`) and class (`BIDSDataGrabber`).
- Add ASL-related filename patterns to the BIDS config file (`nipreps.json`).

Add ASL support

---

niworkflows/interfaces/plotting.py
niworkflows/tests/test_confounds.py
niworkflows/viz/plots.py

Related to https://github.com/nipreps/fmriprep/issues/2614. Once this is merged and there's a new release, I will open a PR to fMRIPrep.
- Add an `ignore_initial_volumes` parameter to the `ConfoundsCorrelationPlot` interface.
- Add an `ignore_initial_volumes` parameter to the `confounds_correlation_plot` function.
- Use the new parameter in related smoke tests.

Add `ignore_initial_volumes` param to `ConfoundsCorrelationPlot`

---

niworkflows/viz/plots.py

Fixes a bug I missed in #843, where the new parameter wasn't actually used.

Correctly use `ignore_initial_volumes` in `ConfoundsCorrelationPlot`

---

niworkflows/func/util.py

For reasons I don't fully understand, the transformation of a template mask for N4 correction could sometimes end up with different qforms and sforms from the reference image. Our attempt to fix up the headers was insufficient, so I'm just copying the whole thing. This fixes the issue, and this image isn't going to be reused in any other context, so the preservation of other header fields seems irrelevant.

FIX: Copy header to ensure mask is really aligned

---

niworkflows/utils/testing.py
niworkflows/utils/tests/test_bids_skeleton.py

This allows creating non-`nii.gz` files through `generate_bids_skeleton`. If no extension is provided, `.nii.gz` will still be used as the default.

ENH: Allow alternative `extensions` when creating a BIDS skeleton

---

niworkflows/viz/plots.py

matplotlib.cm.get_cmap → matplotlib.colormaps
This is new in matplotlib 3.9:
https://github.com/matplotlib/matplotlib/pull/23668
Fixes #865.

MNT: Fix deprectation error in CI

---

.codespellrc
docs/sphinxext/docscrape.py
docs/sphinxext/docscrape_sphinx.py
docs/sphinxext/numpydoc.py

Copied from numpydoc ~~1.6.0~~ 1.7.0.

MNT: update vendored docs files

---

niworkflows/interfaces/nibabel.py
niworkflows/viz/utils.py

ISC001 Implicitly concatenated string literals on one line
This rule is currently disabled because it conflicts with the formatter: https://github.com/astral-sh/ruff/issues/8272

STY: Apply ruff/flake8-implicit-str-concat rule ISC001

---

niworkflows/interfaces/patches.py

Imports the patched FSSource interface from fMRIPrep

PATCH: Modify FSSource to output T2

---

niworkflows/engine/plugin.py
niworkflows/engine/tests/test_plugin.py

Reverted some uses of `config` to the nipype config, which an app should generally be injecting into the nipype workflow config.
Some parts don't exist, so I'm allowing an app config to be passed as a plugin argument "app_config", and falling back to nipype defaults or trivial replacements.
Closes #875.

FIX: Remove accidental MRIQC dependency, allow app config to be passed to workflow plugin

---

niworkflows/interfaces/nibabel.py

FIX: Set cal_max in the NIfTI header for visualization after ``IntensityClip``

---

niworkflows/interfaces/images.py
niworkflows/interfaces/tests/test_images.py

Adds new fields to `TemplateDimensions` iospecs to output a cleaner report if a T2w image was used.
For backwards compatibility, the hardcoded `t1w_*` fields have been left in (as deprecated). They will be removed in a later release (1.14.0)

ADD: Make template dimensions support T2w as well

---

niworkflows/engine/plugin.py
niworkflows/engine/tests/test_plugin.py

Follow-up to #876, which didn't actually test what we wanted it to. We were manually calling `print()` inside the test and interpreting that as being run on process initialization. We need to pass the config to `MultiProcPlugin()`, not `workflow.run()`.
`capsys` does not capture stdout from subprocesses, it seems, so instead I'm telling the subprocesses to touch a file that I choose.

TEST: Fix plugin invocation, use an initializer that can be verified

---

niworkflows/utils/spaces.py

Closes #882.
- To determine dimensionality of a reference space (i.e., surface vs. volume), build a list of 2D standard spaces from templateflow by searching for spaces with a `sphere` file. I also added a constant list of 2D non-standard spaces to check against, although it's currently just `fsnative`.
- The old way looked at the start of the space's name and checked if it began with `fs`, which works for `fsnative`, `fsaverage`, and `fsLR`, but not for `onavg`, `dhcpSym`, or `dhcpAsym`.

Check 2D spaces against list from templateflow

---

.github/workflows/pythonpackage.yml
niworkflows/interfaces/utility.py
niworkflows/viz/plots.py
tox.ini

Failed to put the UV_EXTRA_INDEX_URL in tox so I missed these.

fix: Pandas deprecations

---

niworkflows/anat/ants.py
niworkflows/interfaces/itk.py
niworkflows/interfaces/norm.py
niworkflows/interfaces/tests/test_images.py
niworkflows/interfaces/tests/test_itk.py
niworkflows/reports/core.py
niworkflows/tests/test_segmentation.py
niworkflows/tests/test_utils.py

~~Some changes have been applied using pyupgrade.~~
~~Most~~ All changes have been applied manualy.

STY: Use f-strings where possible

---

niworkflows/interfaces/bids.py
niworkflows/reports/core.py

C409 Unnecessary list comprehension passed to `tuple()` (rewrite as a generator)

STY: Apply ruff/flake8-comprehensions preview rule C409

---

niworkflows/interfaces/bids.py
niworkflows/interfaces/tests/test_bids.py

This came up in https://github.com/nipreps/nibabies/issues/411
Also, adds a default to the expected kwarg `anat_only` to allow bare initialization

ENH: Parse kwargs to allow no T1w

---

niworkflows/utils/connections.py

Using the `list` constructor on a number results in `TypeError: 'int' object is not iterable`
Came up in https://github.com/nipreps/nibabies/pull/445

FIX: Listify numbers

---

niworkflows/data/nipreps.json

Stems from https://github.com/bids-standard/bids-specification/pull/1926, which will take effect in the next BIDS release (v1.11.0).
- Add `+` symbol to the regular expressions for label-based entities in `nipreps.json`.

Allow + symbol in label entities

---

niworkflows/data/nipreps.json

Addresses https://github.com/nipreps/niworkflows/pull/926#discussion_r1970280359.

Remove extra plus signs in regular expressions

---

niworkflows/anat/ants.py
niworkflows/anat/tests/test_ants.py

As discussed in #928, running a masked N4 before calling Atropos can lead to failures, although I don't fully understand why. Nonetheless, passing the output of the first N4 correction resolves the issue in the case I'm looking at as well as brings the workflow into line with `antsBrainExtraction.sh`, which does not do this step.
Furthermore, if `atropos_wf` is called, then N4 is called using the white matter mask at the end, which means this is duplicated effort. This PR rearranges the workflow so that the second top-level N4 is only called if `atropos_wf` isn't created. It also shifts from the pattern:
```py
wf.connect(A)
if condition:
wf.disconnect(A)
wf.connect(B)
```
to:
```py
if condition:
wf.connect(B)
else:
wf.connect(A)
```
I personally find this logic easier to follow and …

fix(brain_extraction): Remove duplicated code, problematic deviation from antsBrainExtraction

---

niworkflows/engine/__init__.py
niworkflows/engine/splicer.py
niworkflows/engine/tests/test_splicer.py

This PR lays some of the groundwork for fMRIPrep extensions.
`splice_workflow` splices a constructed workflow, allowing developers to swap in alternative processing workflows. This works by finding all tagged `Node`/`Workflow` in a graph, and substituting the matching `replacements` workflow. This will require some work in the NiPreps to encapsulate each processing step, likely with a heavy dosing of buffernodes for input and output fields.
Additionally, the `@tag` decorator can be used on any `init_...wf()` factory to facilitate adding the `_tag` attribute.

ENH: Workflow splicer module

---

.circleci/config.yml
.github/workflows/codespell.yml
.github/workflows/docs-build-pr.yml
.github/workflows/docs-build-update.yml
.github/workflows/tox.yml
docs/_static/js/version-switch.js

This will simplify the transition process if/when we change the dev branch name to `main`.
Only thing remaining would be the `    let major_minor = "master";` in the doc version switcher.

chore: Accept main where master is used

---

niworkflows/utils/bids.py

This PR introduces an error on mismatch between `subject`/`session` entities and bids_filters.

FIX: Do not allow filters to overwrite participant / session

---

niworkflows/data/nipreps.json

This PR closes issue #946 by adding PET specific references such as reference PET data with suffix _petref and also confounds PET data with suffix _timeseries. It also adds pet as a datatype.

ENH: update nipreps json

---

niworkflows/utils/bids.py

Fixes https://github.com/nipreps/fmriprep/issues/3474
If the session parameter isn't used, allow overrides from bids filters.

FIX: Loosen session error on mismatch

---

niworkflows/viz/plots.py

* b660fa76d7ef05a529ee1ed483be3095fd517bb9 addresses https://github.com/nilearn/nilearn/issues/5545
* 8653562b39c3da2f0ab9c7779e6d999f3275a4f0 addresses https://github.com/matplotlib/matplotlib/issues/25538 or similar, which seems to be related to `plot_surf` adding its own color bars and then us adding another one. Disabling either fixes the problem, but there's no need to have a colorbar per subplot.

fix: Address failures from nilearn/matplotlib

---

.pre-commit-config.yaml

Running `ruff check` then `ruff format` should always do the right thing.
No need to rerun `ruff check` specifically for `ISC001`.

MNT: no need to re-run `ruff check` after `ruff format`
