- CHANGES.rst
- niworkflows/data/getters.py
- niworkflows/info.py
> [ENH] Remove Google Drive links

- niworkflows/common/report.py
These are moved over from rwblair/issue176 branch of fmriprep.
> Have report capable interface pull cwd from runtime object.

- niworkflows/viz/utils.py
issue https://github.com/poldracklab/niworkflows/issues/26
The cuts nilearn picked are a little different. Nilearn: http://htmlpreview.github.io/?https://github.com/shoshber/pastebin/blob/master/reports/betnilearncuts.html; 
orig: http://htmlpreview.github.io/?https://github.com/shoshber/pastebin/blob/master/reports/betorigcuts.html
@oesteban since you wrote `cuts_from_bbox` can you take a look?
> FIX/WIP (low priority) use established nilearn method to determine cuts

- niworkflows/viz/utils.py
> [RTM] Use 7 cuts in mask/seg

- niworkflows/viz/utils.py
> [RTM] Improve contrast for skull stripping reports

- niworkflows/interfaces/registration.py
- niworkflows/tests/test_reports.py
> [ENH,RTM] Adds the report capable interface of ants.Registration

- Dockerfile
- used shared data folder outside home
- predownload oasis (it's needed for the brain extraction tests)
> [RTM] better atlas caching

- Dockerfile
- niworkflows/data/getters.py
Created a new version, reoriented to RAS using nibabel (no resampling).
Closes #46
> [RTM] Update OASIS template

- niworkflows/interfaces/segmentation.py
- niworkflows/tests/test_reports.py
> [RTM] fixed no segments issue

- niworkflows/common/report.py
- niworkflows/interfaces/registration.py
- niworkflows/tests/test_reports.py
- niworkflows/viz/utils.py
> [RTM] plot masked images if used as an option in coregistration

- niworkflows/viz/utils.py
> [RTM] set image range in a more robust fashion

- niworkflows/common/report.py
- niworkflows/interfaces/registration.py
Fixes https://github.com/poldracklab/fmriprep/issues/222
> [RTM] use only fixed image mask for reports

- niworkflows/common/report.py
- niworkflows/viz/utils.py
This will be useful for plotting effect of ApplyTOPUP
> added labels to registration plots

- niworkflows/common/report.py
> [RTM] use images to define best cuts to display

- niworkflows/common/report.py
> [RTM] better cuts for flirt BBR

- niworkflows/common/report.py
- niworkflows/interfaces/masks.py
- niworkflows/viz/utils.py
> [RTM] aCompCor reportlets

- niworkflows/viz/utils.py
> [RTM] close figures to save memory

- niworkflows/interfaces/registration.py
- Adds the FUGUE interface
- Rename labels in output reportlet
- Add option to set a reference WM contour
> [ENH,RTM] Fieldmap-correction RC interfaces

- setup.py
> [FIX,RTM] Fixed wrong setup.py data path

- niworkflows/interfaces/masks.py
Fixes https://github.com/poldracklab/fmriprep/issues/280. I also excluded NaNs (after dilation) which potentially could deal with https://github.com/poldracklab/fmriprep/issues/276, but I have not tested it on any of those subjects.
> [RTM] add padding to the mask, exclude nans

- Dockerfile
- niworkflows/info.py
add provisions to install bleeding edge packages consistent with fmriprep
> [RTM] update nipype version

- niworkflows/tests/test_reports.py
- niworkflows/viz/utils.py
We will readd this after the release
> Revert "[RTM] blank the values of height"

- Dockerfile
- niworkflows/interfaces/registration.py
- niworkflows/tests/test_reports.py
- niworkflows/viz/utils.py
This is a quick first pass to get Circle to build the artifacts.
Closes #103.
> [MRG] BBRegisterRPT

- niworkflows/info.py
- setup.py
> [RTM] package fixes

- niworkflows/interfaces/__init__.py
- niworkflows/interfaces/registration.py
- niworkflows/tests/test_reports.py
It was half-implemented but commented out.
> [ENH,RTM] Finish up ApplyXFM implementation

- niworkflows/anat/skullstrip.py
So that we fix https://github.com/poldracklab/mriqc/issues/393
> [ENH] Write bias image in skull-stripping workflow

- niworkflows/interfaces/masks.py
- niworkflows/interfaces/segmentation.py
- niworkflows/viz/utils.py
Closes https://github.com/poldracklab/fmriprep/issues/259
> [RTM] Colection of minor visual improvements

- niworkflows/interfaces/registration.py
- requirements.txt
I'm planning to use it in MRIQC
> Moved ref image estimator from FMRIPREP

- niworkflows/interfaces/masks.py
http://stackoverflow.com/questions/3112171/python-assert-with-and-without-parenthesis
One of the reasons why we should not ignore all warnings.
> [RTM] Make assertions actually work

- niworkflows/anat/skullstrip.py
Comes from: https://github.com/poldracklab/mriqc/issues/489
> [ENH] Add 3dUnifize to skull-stripping workflow

- niworkflows/interfaces/registration.py
This is a variant of `SimpleBeforeAfter` that allows either the moving or fixed image to be resampled to the other.
> ENH: Add resampling before/after reporter

- niworkflows/anat/skullstrip.py
> [ENH] Fix skull-stripping workflow when unifize=True

- niworkflows/interfaces/__init__.py
- niworkflows/interfaces/utils.py
It will be useful in mriqc as well (in fact it is probably replicated there)
> [ENH] Copy CopyHeader interface from fmriprep

- niworkflows/data/epi-mni_registration_precise_000.json
- niworkflows/data/epi-mni_registration_precise_001.json
- niworkflows/data/epi-mni_registration_precise_002.json
- niworkflows/data/epi-mni_registration_testing_000.json
- niworkflows/data/epi-mni_registration_testing_001.json
- niworkflows/data/epi-mni_registration_testing_002.json
Necessary since #169 was merged.
> [FIX] Remove initial_moving_transform_com EPI to MNI settings

- niworkflows/anat/mni.py
- niworkflows/info.py
- niworkflows/tests/test_reports.py
Updating the dev version. This should cause errors due to the deprecated interface. I want to verify and resolve those errors before merge.
> [RTM] Update dev version

- niworkflows/anat/skullstrip.py
- requirements.txt
This should be merged and the niworkflows pin be updated in poldracklab/fmriprep#542 before that goes in.
> [RTM] ENH: Use N4BiasFieldCorrection(copy_header=True) in afni_wf

- niworkflows/data/__init__.py
- niworkflows/data/getters.py
- niworkflows/data/utils.py
Fetches test data from Chris' BIDS test repo.
> [ENH] Add a BIDS-examples-1 getter

- niworkflows/interfaces/__init__.py
- niworkflows/interfaces/utils.py
As a result of the code revision going on under https://github.com/poldracklab/fmriprep/issues/225
> [RTM] Integrate utilities from fMRIprep

- niworkflows/viz/utils.py
> [RTM] take TR units into account

- niworkflows/data/getters.py
I've added the [ANTs NKI template](https://osf.io/zdcpw/) to OSF in the attempt to work on skull-stripping. It didn't resolve the issues, but if we want to add the grabber, here's the code.
> [RTM] ENH: Add NKI data grabber

- niworkflows/interfaces/registration.py
poldracklab/fmriprep#711 introduced [`_get_series_len`](https://github.com/poldracklab/fmriprep/blob/24ee939d078296276b613351009b067730fd015b/fmriprep/workflows/bold.py#L1783-L1796) which was a direct copy from `EstimateReferenceImage`. I began by factoring out the relevant code, but didn't end up using it.
If we want to keep these in sync, we can make fmriprep depend on this function. If not, feel free to close.
> [RTM] RF: Factor out _get_vols_to_discard

- niworkflows/interfaces/registration.py
- niworkflows/tests/test_reports.py
See https://github.com/poldracklab/fmriprep/issues/758.
> ENH: Add contours to MRICoregRPT report

- niworkflows/interfaces/mni.py
- niworkflows/tests/conftest.py
- niworkflows/tests/test_registration.py
- niworkflows/tests/test_reports.py
- niworkflows/viz/utils.py
- Ensure str is passed in viz.utils + linting fixes
- Ensure sub-interfaces of RobustMNINormalization do not activate the resource_monitor
- Update nipype pin
> [ENH] Various fixes

- niworkflows/interfaces/utils.py
Addresses poldracklab/fmriprep#800
> [FIX] Increase tolerance in GenerateSamplingReference

- .gitmodules
- niworkflows/viz/utils.py
Updates niworkflows to close file descriptors before forking, using the latest nipype that also does it.
> [FIX] Close file descriptors

- niworkflows/interfaces/utils.py
> [ENH] Lower priority of "Affines do not match" warning

- niworkflows/interfaces/registration.py
This will add an `mri_vol2vol` call for each BOLD series in FMRIPREP, but it should produce better coregistration images without smoothing, which can make assessing the alignment of gray-white boundaries difficult.
> [RTM] ENH: Use nearest for coreg visualization

- .circle/pytests.sh
- niworkflows/info.py
- niworkflows/interfaces/__init__.py
- niworkflows/interfaces/utils.py
This is a port (with modifications) of ValidateImage from FMRIPREP. Modifications to the ValidateImage interface are best viewed using this link https://github.com/poldracklab/niworkflows/compare/132558efe2013588fb2135c464405b16234dd84e...chrisfilo:a9e0d4a4769ddb252d9f99fee6d1930d35a672bf
> Adding SanitizeImage

- Dockerfile
Workaround for https://github.com/conda/conda/issues/6811
> fixing conda version

- niworkflows/interfaces/__init__.py
- niworkflows/interfaces/plotting.py
- niworkflows/viz/plots.py
Updated look and feel (basically removing distracting elements). The colorbar of the carpetplot is:
blue=cortical regions
orange = deep gray matter
green = cerebellum
red = white and csf
> [ENH] Migrate the summary plot to niworkflows

- niworkflows/interfaces/plotting.py
- niworkflows/viz/plots.py
Also updates the wrapper interface for MRIQC to keep working
Preparing for poldracklab/fmriprep#174 and poldracklab/fmriprep#877
> [ENH] fMRI summary plot to take ``_confounds.tsv``

- niworkflows/viz/utils.py
While creating the ICA-AROMA reports.
> [FIX] ValueError: invalid literal for int()

- niworkflows/__about__.py
@oesteban Made this a PR just in case I've forgotten how we do this...
> Bump dev version to 0.3.12-dev

- niworkflows/interfaces/mni.py
Starting by manually rebasing #121 onto current master
Closes #121.
> [ENH] Constrained cost-function masking for T1-MNI registration

- niworkflows/data/getters.py
This PR related to poldracklab/fmriprep#1145. Use new uploaded template file.
> FIX: DTK template name

- niworkflows/__about__.py
- niworkflows/interfaces/utils.py
Required for poldracklab/fmriprep#1180.
> PIN: nipype 1.1.0

- niworkflows/interfaces/tests/test_images.py
Ref #265. Upstream missed out tests on ``SignalExtraction``.
> [TST] Add tests missed out in #263

- niworkflows/utils/bids.py
> [FIX] ``get_metadata_for_nifti`` broken in transfer from fmriprep

- niworkflows/interfaces/bids.py
Better handling of paths (via pathlib), lists of inputs, and ``extra_values``
> [RF] Improve implementation of DerivativesDataSink

- niworkflows/utils/bids.py
> [HOTFIX] Fix ``UnboundLocalError`` in utils.bids

- .circleci/config.yml
- codecov.yml
- niworkflows/__about__.py
- tox.ini
> CI: Backport coverage to maint/0.5 branch

- niworkflows/utils/misc.py
- niworkflows/utils/tests/test_utils.py
Fixes poldracklab/fmriprep#1480
> [ENH] Do not save the original name and time stamp of gzip files

- niworkflows/interfaces/bids.py
> [FIX] Do not cast ``run`` BIDS-entity to string

- niworkflows/anat/ants.py
- niworkflows/data/antsBrainExtractionNoLaplacian_precise.json
- niworkflows/data/antsBrainExtractionNoLaplacian_testing.json
- niworkflows/data/antsBrainExtraction_precise.json
- niworkflows/data/antsBrainExtraction_testing.json
I'm checking both workflows command-by-command, so I'll be gathering here the changes necessary to make them fully dual.
> [FIX] Revising antsBrainExtraction dual workflow

- niworkflows/anat/ants.py
Addresses https://github.com/poldracklab/smriprep/pull/57/files#r263938034
> [ENH] Expose bias-corrected T1w before skull-stripping

- niworkflows/interfaces/confounds.py
- niworkflows/tests/test_confounds.py
- niworkflows/viz/plots.py
* Resolves #320 
* Always include global signal in correlation plot
* Don't drop columns with duplicate values (leads to confusing behaviour or crashes, particularly if all-NA duplicates are dropped)
> ENH: Update CompCor plotting to allow getting NaNs

- niworkflows/anat/ants.py
This PR adds a node to the `antsBrainExtraction` workflow to ensure that the mask produced matches the xform matrices and codes of the original reference image, and sets some other relevant metadata of the headers.
> ENH: Ensure brain mask's conformity

- niworkflows/interfaces/bids.py
Add a new ``meta_dict`` input to ``DerivativesDataSink``s, so that this can be done:
```Python
>>> dsink = DerivativesDataSink(base_directory='/path/to/BIDS/derivatives', check_hdr=False,
...                             SkullStripped=True)
>>> dsink.inputs.in_file = 'output_file_to_store.nii.gz'
>>> dsink.inputs.source_file = 'sub-10/func/sub-10_task-rest_run-1_bold.nii.gz'
>>> dsink.inputs.keep_dtype = True
>>> dsink.inputs.desc = 'preproc'
>>> dsink.inputs.RepetitionTime = 0.75
>>> dsink.inputs.meta_dict = {'RepetitionTime': 1.75, 'SkullStripped': False, 'Z': 'val'}
```
In the example, ``RepetitionTime`` and ``SkullStripped`` will be overriden by the values passed in dynamically, and ``Z`` will be added to the output metadata.
cc @rciric
> ENH: ``DerivativesDataSink`` now accepts metadata dictionaries too

- niworkflows/interfaces/bids.py
Permits setting a list of ``allowed_entities`` at the instantiation time
of ``DerivativesDataSink``s so that it is possible to create arbitrary,
dynamic BIDS entities for the output file name without confusion with dynamic
metadata keys.
The reason to add this feature is to allow a more flexible interface for
derivatives generated via iterables in the context of
poldracklab/fmriprep#1558.
> ENH: Add an ``allowed_entities`` setting in ``DerivativesDataSink``

- niworkflows/interfaces/bids.py
- niworkflows/interfaces/tests/test_bids.py
> FIX: BusError in ``DerivativesDataSink``

- niworkflows/viz/plots.py
This PR cleans up the code a little bit, and fixes poldracklab/fmriprep#1620
> FIX: Refine implementation of plotting confounds correlations

- niworkflows/interfaces/segmentation.py
This is currently a proof-of-concept. We should decide what the appropriate output should be. This is an SVG file, so I don't think it's quite as easy as an HTML snippet... @oesteban What would you like the output to be?
Closes #336.
Addresses poldracklab/mriqc#779.
> ENH: Create informative HTML reportlet on missing MELODIC mix

- niworkflows/func/util.py
Necessary for poldracklab/fmriprep#1653.
> RF: Move BOLD-reference generation workflows to niworkflows

- niworkflows/interfaces/utils.py
- niworkflows/tests/data/confounds_metadata_short_test.tsv
- niworkflows/tests/test_viz.py
- niworkflows/viz/plots.py
* Resolves poldracklab/fmriprep#1680 and adds a unit test to cover the singleton case
> Handle singleton decompositions: fix poldracklab/fmriprep#1680

- .zenodo.json
Wasn't sure if it was appropriate for me to `[skip ci] ` for a non-code edit.
> Update .zenodo.json 

- .circleci/config.yml
- .travis.yml
- niworkflows/anat/ants.py
- niworkflows/func/util.py
- niworkflows/interfaces/fixes.py
- setup.cfg
> FIX: Nonpositive values entered to N4 when calculating BOLDrefs

- niworkflows/interfaces/bids.py
- niworkflows/interfaces/tests/test_bids.py
Generally reworked the interface and added a couple tests. Going to target full coverage on this, so checking codecov...
Begins to address https://github.com/poldracklab/smriprep/issues/27
> ENH: Enable BIDSFreeSurferDir to take an absolute path as a subjects directory

- niworkflows/reports/core.py
- setup.cfg
Accommodates bids-standard/pybids#496.
Fixes #404.
> FIX: Do not validate built paths

- CHANGES.rst
- README.rst
- docs/api.rst
- docs/changelog.rst
- docs/conf.py
- docs/index.rst
- docs/installation.rst
- docs/links.rst
- long_description.rst
- niworkflows/__init__.py
- setup.cfg
> DOC: Maintenance of the documentation building

- niworkflows/reports/fmriprep.yml
- niworkflows/reports/tests/test_core.py
> ENH/TEST: Add all valid entities to fmriprep report specification

- niworkflows/utils/misc.py
- niworkflows/utils/tests/test_utils.py
instead of deleting and remaking (https://github.com/nipy/nipype/blob/792988f19c427c6f631df4d38a5942063f4b8d46/nipype/utils/filemanip.py#L768) (lol docstring), keep and clean directory
> ENH: Add helper function for cleaning a directory

- niworkflows/interfaces/bids.py
> ENH: Downgrade log level for superfluous scans

- .circleci/config.yml
- .codecov.yml
- .dockerignore
- .travis.yml
- Dockerfile
- setup.cfg
Some omitted files are being included on the report - the ``setup.cfg`` file is not being respected.
> MAINT: Revise code coverage collection

- niworkflows/interfaces/images.py
- niworkflows/interfaces/itk.py
- niworkflows/interfaces/masks.py
- niworkflows/interfaces/utils.py
- niworkflows/reports/core.py
- niworkflows/utils/images.py
- niworkflows/viz/utils.py
Also completes #472 by addressing https://github.com/nipreps/niworkflows/pull/472#discussion_r386630986
> MAINT: Pacify security patterns found by Codacy

- niworkflows/utils/spaces.py
Helps I/O of the config file being drafted for fMRIPrep (https://github.com/poldracklab/fmriprep/pull/2018)
> ENH: Overwrite attr's string conversion dunders

- niworkflows/cli/run.py
- setup.cfg
Adds a scaffold to allow quick implementation of command-lines wrapping the internal workflows.
> ENH: Transfer brain mask script from *fMRIPrep*

- niworkflows/interfaces/plotting.py
- niworkflows/tests/test_viz.py
- niworkflows/viz/__init__.py
- niworkflows/viz/plots.py
This addresses poldracklab/fmriprep#2026 with the idea of replacing the current volumetric carpetplot with a surface/voxel hybrid.
An example rendered image:
This includes 4 groupings: left and right cortices (dark/light blue respectively), subcortical structures (orange), and cerebellum (green).
> ENH: CIFTI carpetplot

- niworkflows/interfaces/bids.py
- set boldref suffix default to match source dtype
addresses poldracklab/fmriprep#2000
> ENH: add option to match source dtype

- niworkflows/viz/__init__.py
- niworkflows/viz/notebook.py
- niworkflows/viz/plots.py
- niworkflows/viz/utils.py
Add a little wrapper around our registration reportlet to allow them to render (and flicker) within a notebook.
Created for poldracklab/nitransforms#93.
@mgxd this little trick could help you iterate on #491 faster.
> ENH: Show registration reportlets inline within Jupyter notebooks

- niworkflows/reports/figures.json
I'd appreciate a quick thumbs-up :)
> FIX: Add DWI default patterns for dMRIPrep's reportlets

- niworkflows/utils/misc.py
- niworkflows/utils/tests/test_misc.py
> ENH: Add utility function to quickly check FS license

- .travis.yml
- niworkflows/anat/ants.py
- niworkflows/interfaces/images.py
- niworkflows/interfaces/masks.py
- niworkflows/interfaces/tests/test_bids.py
- setup.cfg
Builds off #520,
pip needs to be upgraded to >= 19.0.2 to be compatible with versioneer https://github.com/pypa/pip/issues/6163#issuecomment-462014864
also style checks were failing due to ambiguous variables.
> MAINT: fix failing travis build

- niworkflows/reports/core.py
- niworkflows/reports/tests/test_core.py
Spotted in https://github.com/poldracklab/fmriprep/pull/2113
> FIX: Purge troublesome lstrip

- docs/requirements.txt
- niworkflows/interfaces/nitransforms.py
- setup.cfg
Resolves: #524.
References: poldracklab/smriprep#188
> ENH: Upstream NiTransforms module from fMRIPrep

- niworkflows/func/util.py
Completes poldracklab/fmriprep#2147
> FIX: ``MultiLabel`` interpolations should not use ``float=True``

- niworkflows/viz/utils.py
> FIX: Use ``numpy.linspace`` to calculate mosaic plots' cutting planes

- niworkflows/utils/spaces.py
> FIX: Add DWI nonstandard spaces

- CHANGES.rst
FYI (assumes merging #567 into master).
> REL: 1.3.1

- niworkflows/interfaces/bids.py
- niworkflows/interfaces/tests/test_bids.py
> FIX DerivativesDataSink warning when it has multiple source files

- niworkflows/interfaces/bids.py
- niworkflows/interfaces/tests/test_bids.py
First step of https://github.com/nipreps/fmriprep/issues/2294.
> FIX: Cordon off .dtseries.json contents

- .circleci/config.yml
Incorporates https://github.com/nipreps/fmriprep/pull/2295 and https://github.com/nipreps/fmriprep/pull/2316
> CI: CircleCI housekeeping

- niworkflows/anat/coregistration.py
- niworkflows/anat/freesurfer.py
- niworkflows/interfaces/freesurfer.py
References: nipreps/dmriprep#125.
> ENH: Upstream *fMRIPrep*'s ``init_bbreg_wf`` to integrate it in *dMRIPrep*

- niworkflows/data/nipreps.json
Part-of: nipreps/sdcflows#123.
> ENH: Revise some patterns of the BIDSLayout config to aid SDCFlows new API

- niworkflows/func/util.py
- niworkflows/interfaces/bold.py
- niworkflows/interfaces/images.py
- niworkflows/interfaces/registration.py
- niworkflows/interfaces/tests/test_images.py
> ENH: Add a ``RobustAverage`` interface and split volume selection

- .circleci/config.yml
- niworkflows/tests/conftest.py
Finalizes the migration from zipfiles to datalad datasets.
> MAINT: Migrate ``ds003_downsampled`` to ``nipreps-data``

- .circleci/config.yml
- docs/api.rst
- niworkflows/conftest.py
- niworkflows/func/tests/test_util.py
- niworkflows/interfaces/nibabel.py
- niworkflows/workflows/epi/refmap.py
- niworkflows/workflows/epi/tests/test_refmap.py
- setup.cfg
> ENH: Cross-cutting (modalities, species) workflow to generate EPI references

- niworkflows/interfaces/nibabel.py
This is done to aid the new SDC-SyN workflow.
> ENH: Add an inversion operation to ``IntensityClip``

- niworkflows/viz/utils.py
- setup.cfg
Originally #619 (see https://github.com/nipreps/niworkflows/pull/619#issuecomment-777772466)
> FIX: Update svgutils after breaking API changes

- niworkflows/interfaces/bids.py
- niworkflows/interfaces/tests/test_bids.py
- niworkflows/utils/images.py
Closes #640.
Would be glad for some inputs on these tests from @glatard et al.
> RF: Write derivatives once, using deterministic gzip settings

- .circleci/config.yml
- .dockerignore
- Dockerfile
- Makefile
- docker/files/nipype.cfg
- niworkflows/func/tests/test_util.py
- niworkflows/tests/conftest.py
- setup.cfg
> [BACKPORT] CI: Use datalad-managed test data

- Dockerfile
Test to supplement https://github.com/nipreps/fmriprep/pull/2647
> TST: Update to FSL6

- niworkflows/utils/tests/README.md
- niworkflows/utils/tests/bids.py
- niworkflows/utils/tests/test_bids_skeleton.py
Supercedes https://github.com/nipreps/nibabies/pull/156
Useful for https://github.com/nipreps/sdcflows/pull/257
> ENH: Add utility function to generate sample BIDS directory

- niworkflows/interfaces/nibabel.py
- niworkflows/interfaces/tests/test_nibabel.py
Porting over interfaces created within nibabies
> ENH: Additional nibabel interfaces

- niworkflows/viz/plots.py
Simple implementation of reordering of rows in the carpetplot using hierarchical clustering. Supersedes #684.
> ENH: Reorder within-segment rows of carpetplot with hierarchical clustering

- niworkflows/utils/timeseries.py
I introduced this error in #688. Currently running locally with fMRIPrep to test the but has been indeed fixed.
> FIX: Error handling the segmentation in NIfTI extraction

- niworkflows/utils/misc.py
> FIX: Account for potential lists of lists in multi-echo cases

- niworkflows/data/epi_atlasbased_brainmask.json
- niworkflows/func/util.py
> FIX: Address some reliability issues of the functional masking workflow

- setup.cfg
@oesteban Is this safe to do in a patch release?
> MNT: Relax nitransforms dependency

- niworkflows/viz/utils.py
It would be wonderful to have https://github.com/nipreps/niworkflows/pull/728 available to the LTS release :-)
> [BACKPORT] FIX: Stop relying on deprecated indexing behavior

- niworkflows/interfaces/cifti.py
- niworkflows/interfaces/nibabel.py
- niworkflows/interfaces/tests/test_nibabel.py
Ports over a new interface implemented in https://github.com/nipreps/nibabies/pull/229
No rush in getting this in, would like a review whenever vacations are over
> ENH: ReorientImage interface

- niworkflows/interfaces/images.py
Trivial improvements to the existing interface:
- Re-enable the output of HMC matrices for AFNI's ``3dVolReg``
- Map the realigned file of references to an output of the interface for further use.
> FIX: Missing outputs in ``RobustAverage``

- niworkflows/interfaces/tests/test_utility.py
- niworkflows/interfaces/utils.py
Backports #746 to the LTS series
> FIX: TSV2JSON should convert empty TSV files to empty JSON files

- .circleci/config.yml
- .github/workflows/pythonpackage.yml
- niworkflows/tests/generate_data.py
- niworkflows/viz/plots.py
- setup.cfg
> FIX: Use nilearn plot_surf over surfplot

- niworkflows/interfaces/bids.py
- niworkflows/interfaces/tests/test_bids.py
Closes https://github.com/nipreps/fmriprep/issues/2869
> MAINT: Remove non-compliant `dtseries.json` metadata

- setup.cfg
This may be what's causing the build failures in https://github.com/nipreps/fmriprep/actions/runs/3526235444/jobs/5913920552
> MAINT: Loosen dependency versions

- CHANGES.rst
- niworkflows/interfaces/nibabel.py
> DOC: 1.7.0 release notes

- .circleci/config.yml
> CI: Update CircleCI from master

- niworkflows/viz/utils.py
Should resolve various plotting issues.
> FIX: Use correct image for contour plotting

- .circleci/config.yml
> CI: Build and upload wheels

- .github/dependabot.yml
> MNT: Configure dependabot to upgrade actions

- .github/workflows/pythonpackage.yml
See https://github.com/orgs/community/discussions/16109 for further discussion. For now, it just adds if switchs to each job.
> MAINT: Do not run scheduled builds on forks

- niworkflows/anat/ants.py
- niworkflows/interfaces/norm.py
- niworkflows/utils/misc.py
Addressing https://github.com/templateflow/templateflow/issues/149
> FIX: Inspect if template has resolution instead of assuming

- CHANGES.rst
Release prep for 1.8.0, for immediate release.
> REL: 1.8.0

- docs/sphinxext/docscrape.py
- docs/sphinxext/docscrape_sphinx.py
- docs/sphinxext/numpydoc.py
Copied from [numpydoc 1.5.0](https://github.com/numpy/numpydoc/tree/3a8a96cda5e04ef77caa076be1fcd115e3987b62/numpydoc).
> MNT: update vendored docs files

- niworkflows/interfaces/reportlets/registration.py
- niworkflows/interfaces/tests/test_bids.py
- niworkflows/viz/plots.py
- niworkflows/viz/utils.py
Should fix pre-release checks.
> FIX: Replace deprecated Matplotlib functionality

- niworkflows/data/nipreps.json
Required for https://github.com/nipreps/smriprep/pull/416
> ADD: Parsing for `space+cohort` structure

- niworkflows/interfaces/conftest.py
PGH003 Use specific rule codes when ignoring type issues
> SYT: Apply ruff/pygrep-hooks rule PGH003

- CHANGES.rst
> rel: 1.13.0

- .pre-commit-config.yaml
Changes:
```
ruff (legacy alias)......................................................Passed
```
into:
```
ruff check...............................................................Passed
```
> MNT: Update pre-commit ruff legacy alias
